### ISSUE TITLE
add landing page for /file area

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1008]
Because this bites me every time I try to remember how to upload photos: there should be a page at dreamwidth.org/file that links to file/new and file/edit.

**Comment by kareila** [comment]
This didn't get auto-closed.

For future reference, @hotlevel4: when submitting a pull request, please include the text "fixes #[num]" (where [num] is the number of the related issue) in the text of the PR, so that the issue will automatically be marked as closed when the PR is merged.  Just referencing the issue number won't make the automatic closing happen. Thanks!  :)

**Comment by hotlevel4** [comment]
I've been using "Fixes issue #[num]" -- does it not work with the word issues there?

**Comment by kareila** [comment]
It looks like it doesn't work unless the verb directly precedes the issue number.

Here is the GH help page on the subject: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by hotlevel4** [comment]
Got it, sorry about that!

**Comment by kareila** [comment]
No worries! Glad to have you on the team :)
