### ISSUE TITLE
Code tour tool

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1096]
Replace the functionality of the old code tour tool: 

* aim it at dw-free and dw-nonfree (I would be okay with running the tool twice, once for each repository)
* enter the desired start and end date, with end date defaulting to "today" in such a way that it doesn't accidentally not pick up things which were resolved today (so today at 23:59:59 or tomorrow at 00:00:00)
* return a code tour template
 * Link to resolved pull request
 * link to issue, if any
 * name the accounts checking in code
 * auto-create links to contributors' user accounts on github 
 * Make a place to enter a description
 * include multiple contributors on each checkin if possible 
* Create a summary
 * count the number of items in the completed tour
 * list the contributors neatly

**Comment by afuna** [comment]
Raw commandline script here:

https://gist.github.com/afuna/46726e4ab225e45f5888

Notes:

* runs on both dw-free and dw-nonfree and merges related issues into one item
* pull requests that are in response to an issue are not duplicated but will have their links included in the same item
* all closed items are included, whether that was FIXED or WONTFIX, etc, since there's no easy way to tell
* takes a start date. end date is assumed to be today / this very moment
* returns a code tour template with link to pull request, issue, github accounts, space to enter a description
* not included: "name the accounts checking in code" (not sure what that means!)
* not included: "include multiple contributors on each checkin" -- hard to automate because there's usually only one assignee to the pull request, etc. This can be done manually if context requires
* summary included (note: may need to be updated for any issues closed WONTFIX)

**Comment by Sophira** [comment]
I installed the requests module on the Dreamhack server (which this script needs) and ran it for a test output, which can be found at http://hack.dreamwidth.net/dev/temp-codetour-output.txt.

**Comment by afuna** [comment]
Thanks!

**Comment by afuna** [comment]
Hmm, so about hosting this, should we try to host it with a web interface somewhere, or just have someone run the commandline entry each time?

**Comment by Sophira** [comment]
As I said, I'll gladly host it. I had just been waiting to see if there were any comments on the output from anybody. Since there don't seem to be any, I'll get it up and running now.

**Comment by afuna** [comment]
Awesome thank you!

**Comment by afuna** [comment]
Closing this since we've got it in place! Any further reported bugs can go into their own issues :)
