### ISSUE TITLE
Browsing via HTTPS gives 404 or directs to DW main page

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#1123]
I can go to http://wiscon.dreamwidth.org/ or http://dw-news.dreamwidth.org/ to see those communities; if I go to https://wiscon.dreamwidth.org/ or https://dw-news.dreamwidth.org/ (the HTTPS versions) then the page content is the DW main page (the URL stays the same). And, even if I was logged in, the site looks as though I am not logged in (a blank set of user/pass boxes).

I can read http://dw-news.dreamwidth.org/36470.html and http://wiscon.dreamwidth.org/118455.html just fine, but when I try going to them via HTTPS I get a 404 error.

Going to https://brainwane.dreamwidth.org/read also gives me a 404.

Going to https://brainwane.dreamwidth.org/profile redirects me to https://www.dreamwidth.org/?returnto=/profile.bml and shows me the logged-in version of the DW main page.

**Comment by brainwane** [comment]
I see [a few other people have also run into this](http://dw-news.dreamwidth.org/36470.html?thread=5123446#cmt5123446).

**Comment by zorkian** [comment]
All of the 404s should be fixed.

When I set up the nginx proxy, I had forgotten to pass through the `Host` header, so we were passing through a constant header instead of the actual host being hit by the user.

Going to resolve this ticket, but please keep us posted with your test results -- either in GHI or in news comments! And thank you!
