### ISSUE TITLE
Whitelist embeds from jigsawplanet.com

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1200]
http://www.dreamwidth.org/support/see_request?id=30366

Sample code I've found at http://www.jigsawplanet.com/?rc=embedpuzzle&pid=31cbc323bb16:

```
<iframe style="width:100%;height:600px" frameborder=0 allowfullscreen src="//www.jigsawplanet.com/?rc=play&amp;pid=31cbc323bb16&amp;view=iframe" title="Pumpkins - online jigsaw puzzle - 48 pieces">[Your web browser does not support frames or is currently configured not to display frames. However, you may visit <a href="http://www.jigsawplanet.com/?rc=play&amp;pid=31cbc323bb16" target="_top">the related page</a>.]</iframe>
```

**Comment by hotlevel4** [comment]
The following snippet passes embed-whitelist.t but does not actually embed the video, probably related to other background embed stuff I cannot seem to figure out:

    if ( $uri_host eq "www.jigsawplanet.com" ) {
        return ( 1, 1 ) if $parsed_uri->query =~ m/rc=play&amp;pid=[a-z0-9]+&amp;view=iframe/;
    }

**Comment by afuna** [comment]
The $parsed_uri->query actually returns & instead of &amp;in the relevant places. 

Hmmm, but on further thought, we can't control the order of things in the query and those are more likely to be in a different order than with the bare URI. And we mostly just care enough to make sure we don't whitelist the entire site (so that for sites which can be used to host basically anything can't be used to embed malicious scripts).

We might be able to get away with just one reasonable identifier -- maybe rc=play is enough?
