### ISSUE TITLE
t/post.t is broken

### ISSUE THREAD

**Issue by anall** [dreamwidth/dw-free#1220]
I have been fixing ALL the tests after the move to a separate test DB.

However, this seems like code-break, not test-break.

**Comment by BritneyS** [comment]
I'll claim this one.

**Comment by rahaeli** [comment]
Hi Britney! The auto-assign bot didn't assign you, because you need to be added to the team. Before I can do that, I need your Contributor Licensing Agreement aka CLA, which can be found in the <a href="https://github.com/dreamwidth/dw-cla">dw-cla</a> repository. Just download either the pdf or the doc, print the last page, sign it, and return it.

(You can return it a bunch of ways, but the easiest is probably taking a photo of the signed last page and sending me the photo.)

Once you've done that, I'll assign you to this issue and add you to the team so you can claim issues and have them assigned to you by the auto-assign bot!

**Comment by rahaeli** [comment]
lol bot.

**Comment by BritneyS** [comment]
Ok. I can get that to you tomorrow (I'm in the GMT-5 time zone).

**Comment by rahaeli** [comment]
No rush! As long as we have it by the time you submit your first pull request, it'll be fine. If you've got any questions about the contents, just let me know. (It's basically "you license your contribution to us, we promise not to sue you if there's bugs in it", more or less.)

**Comment by kareila** [comment]
Most of this is fixed in #1350 but two tests are still failing and I know why, but not what to do about it.

`Failed test 'valid entry posted to alt (not remote)' at t/post.t line 545.`
`Failed test 'no such entry (was posted to alt)' at t/post.t line 548.`

The reason these fail is because `post_as_other` support was removed from DW::Controller::Entry::_auth in fdb2098e353619f1d158abfcfb42fa1a24d930b5.

**Comment by afuna** [comment]
I think it’s safe to remove them since we removed the backing
functionality!

(That is, they’re doing what the test is supposed to do: warn us that
something has changed, but in this case that change was deliberate :))

**Comment by kareila** [comment]
So there's no way any more to do whatever it is it's trying to do?  I'm still a bit fuzzy on the particulars.

**Comment by afuna** [comment]
Yup. We can remove that whole section.

We no longer allow remote users to post to an alt personal account while logged in. The first test checks that it was posted to the alt journal. The second test checks that it was not posted to the remote's journal.

**Comment by kareila** [comment]
Thanks for the explanation :)
