### ISSUE TITLE
Modals in /entry/new don't work in Opera (Presto)

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1225]

**Comment by deborahgu** [comment]
This problem seems to be in multiple versions of Presto (O 10, 12), but I am pretty sure not Webkit or Blink.

**Comment by afuna** [comment]
Oops sorry for some reason I thought that it was Blink that was called the older version :)

**Comment by deborahgu** [comment]
okay, PRs on free and non-free. It's an easy fix though I wish I understood better what the problem is.

**Comment by zorkian** [comment]
Opera is not a supported browser.

**Comment by rahaeli** [comment]
Even for non-supported browsers, though, we've always tried to fix "this thing is completely broken and the person using this browser can't use the site" if it's a quick fix -- the root of this bug was a report in dw-beta of someone now unable to post entries. Can we investigate the change more thoroughly to verify it won't have negative effects?

**Comment by zorkian** [comment]
Well, sure -- that's up to you if you want to investigate.

Hacks for browser support are what I'm against, mostly. We are just now getting out of a world where we had to add `<!--[if IE 6]>` to everything, and I don't want to go back. I think our rule of thumb should be "if we can tweak* an existing bit of code to support XYZ browser, that's probably fine, but if we have to add a hack/unique code for it, then no".

Hacks add complexity and have unintended side effects on other browsers. They also cost a lot of time for our reviewers who have to verify that the hack has no side effects on other browsers, plus have to spool up the mental state to really understand what is going on. It's just a bad deal all around.

* Tweak is kind of undefined. I am thinking things like "we already use z-index, but XYZ behaves better if we set it to values less than 10, and that works in all browsers" or "instead of `red` we use `#ff0000`". Those seem reasonable.

**Comment by deborahgu** [comment]
I tested it in other browser and it does seem stable. It seems to be a really common fix, and has no effect as far as I can see on the operation of Foundation in any other way.

**Comment by deborahgu** [comment]
If I were to do or find an analysis of what this does, will you reconsider?

**Comment by deborahgu** [comment]
Okay, here's what's going on, and this is SO WEIRD. Based on looking at the Foundation code 

https://github.com/zurb/foundation/blob/master/js/foundation/foundation.js#L385-404

And this convo in the commit message:

https://github.com/zurb/foundation/commit/ed4b8fbd9c61f56e06429ee44f9ac433db8c5c96#comments

"namespace", in this conversation, is populated by "font family". Cf.

https://github.com/zurb/foundation/blob/7c0f22df733a7b5a1995aca1eb2e3396a3438a13/scss/foundation/components/_global.scss#L396-398

In other words, this code is an _awful_ hack. As you can see from 

https://github.com/zurb/foundation/blob/7c0f22df733a7b5a1995aca1eb2e3396a3438a13/scss/foundation/components/_global.scss#L341-398

They are using the font-family applied to meta tags -- since that will never be used -- as a way of putting settings in CSS.  This isn't a standard SCSS thing, is it? Doesn't look like it to me.

So anyway, this breaks Opera Presto (and some JS test frameworks) which, if a font-family is requested when it's undefined, explicitly return the calculated font family instead of undefined.

In our case, this is safe, because we never set namespace anywhere, so this process of setting it to blank is harmless (and in fact would be performed by the set_namespace function if Opera didn't choke on the returned calculated font). However, if we want to be extra special careful, I could replace it with a "if namespace is undefined, set namespace to ''." It might be a little tricky because I'd still have to deal with the Opera clever-boots return value, but I could make it work, I'm sure.

**Comment by zorkian** [comment]
Thank you for doing the research, that makes me feel better about the
safety of the change, but I still don't think we should do it.

Basically, I don't think we should be putting in custom code to support
an unsupported browser. This increases the complexity of our own code
and, IMO, the cost outweighs the gain.

Philosophically, we are just now getting away from a world where we had
to do crazy custom hacks for other browsers, so I don't think it's a
good decision for us (or anybody!) to go back down that path. (And yes,
I know we're not totally out of the woods, but we're getting better. And
in our case, we're delegating that work to Zurb's Foundation, which
frees us up to focus on our own project.)

I think that the line has to be drawn somewhere. I personally draw it on
adding custom code to support one-off browsers that are not in our
supported list.

--
Mark Smith mark@qq.is


On Tue, Feb 17, 2015, at 04:52 PM, Deborah Kaplan wrote:
> Okay, here's what's going on, and this is SO WEIRD. Based on looking
> at the Foundation code


> https://github.com/zurb/foundation/blob/master/js/foundation/foundation.js#L385-404


> And this convo in the commit message:


> zurb/foundation@ed4b8fb#comments[1]


> "namespace", in this conversation, is populated by "font family". Cf.


> https://github.com/zurb/foundation/blob/7c0f22df733a7b5a1995aca1eb2e3396a3438a13/scss/foundation/components/_global.scss#L396-398


> In other words, this code is an *awful* hack. As you can see from


> https://github.com/zurb/foundation/blob/7c0f22df733a7b5a1995aca1eb2e3396a3438a13/scss/foundation/components/_global.scss#L341-398


> They are using the font-family applied to meta tags -- since that will
> never be used -- as a way of putting settings in CSS. This isn't a
> standard SCSS thing, is it? Doesn't look like it to me.


> So anyway, this breaks Opera Presto (and some JS test frameworks)
> which, if a font-family is requested when it's undefined, explicitly
> return the calculated font family instead of undefined.


> In our case, this is safe, because we never set namespace anywhere, so
> this process of setting it to blank is harmless (and in fact would be
> performed by the set_namespace function if Opera didn't choke on the
> returned calculated font). However, if we want to be extra special
> careful, I could replace it with a "if namespace is undefined, set
> namespace to ''." It might be a little tricky because I'd still have
> to deal with the Opera clever-boots return value, but I could make it
> work, I'm sure.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/zurb/foundation/commit/ed4b8fbd9c61f56e06429ee44f9ac433db8c5c96#comments
  2. https://github.com/dreamwidth/dw-free/issues/1225#issuecomment-74789247

**Comment by rahaeli** [comment]
I disagree completely. This isn't like adding separate JS that only runs in IE6 or overriding/forking a module in Foundation -- if that were the case I'd definitely agree that it wasn't something we should be doing, because that does incur overhead.

This, though, is a one-line change in the templates that we've written on our end, to work around a bug in Foundation that makes a major function of the site (posting entries) not work for a subset of our users. Admittedly, it's only 1.25% by current stats, but posting entries is probably the single most critical function of the site. (Well, okay, probably posting comments is the most critical, but entries is a close second.)

It incurs no overhead on our part to make the change, and going by the links @deborahgu has provided, we lose nothing by doing it -- it doesn't prevent any part of Foundation from working. I also did a quick Github search and found over 500 instances of the line in question, so we wouldn't be the only ones doing it -- in fact, the default Foundation JS template gives that line as an example of something you might want to do in other contexts.

**Comment by zorkian** [comment]
It's not a bug in Foundation. Something that works in Firefox, Chrome,
Safari, and Internet Explorer but not in Opera is not because there's a
bug in Foundation. There's a problem in Opera, but more importantly:
just _old versions_ of Opera.

Our site works fine in the latest/stable version of Opera. For
non-supported browsers, where the problem is fixed by upgrading, that
should be our answer; we really shouldn't hack around to support older
versions of already unsupported software. When you exclude the Opera
users who have upgraded to a version of their browser that works just
fine, that 1.25% gets a lot smaller.

And also, how did you find 500 instances of people doing this? I only
see 23 instances
(https://github.com/search?p=1&q=%22foundation.global.namespace+%3D+%27%27%3B%22&ref=searchresults&type=Code&utf8=%E2%9C%93);
the rest of the pages are just people who have checked in copies of
foundation.js. (And anyway, cargo cult programming is not a good idea.)

Anyway, the root of the issue here is a bad JavaScript engine in an
abandoned browser: the old Presto version last had a major release in
2012, and hasn't even had security patches since 2013. I don't want to
carry around hacks to make it work.

--
Mark Smith mark@qq.is


On Tue, Feb 17, 2015, at 07:11 PM, Denise Paolucci wrote:
> I disagree completely. This isn't like adding separate JS that only
> runs in IE6 or overriding/forking a module in Foundation -- if that
> were the case I'd definitely agree that it wasn't something we should
> be doing, because that does incur overhead.


> This, though, is a one-line change in the templates that we've written
> on our end, to work around a bug in Foundation that makes a major
> function of the site (posting entries) not work for a subset of our
> users. Admittedly, it's only 1.25% by current stats, but posting
> entries is probably the single most critical function of the site.
> (Well, okay, probably posting comments is the most critical, but
> entries is a close second.)


> It incurs no overhead on our part to make the change, and going by the
> links @deborahgu[1] has provided, we lose nothing by doing it -- it
> doesn't prevent any part of Foundation from working. I also did a
> quick Github search and found over 500 instances of the line in
> question, so we wouldn't be the only ones doing it -- in fact, the
> default Foundation JS template gives that line as an example of
> something you might want to do in other contexts.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/deborahgu
  2. https://github.com/dreamwidth/dw-free/issues/1225#issuecomment-74803876
