### ISSUE TITLE
Add a link to view the message to the "Message sent" page

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1232]
From http://dw-suggestions.dreamwidth.org/1360416.html:

> Suggest adding a link to the "Your message has been sent successfully" page, so the sender can easily view the sent message.

**Comment by woggy** [comment]
So, I touched on this in the commit message, but I did want to discuss it a bit more. Since PMs run through the ESN worker(s), there's a chance that the user will click through to the inbox page before the worker's finished propagating the new message through. The worker seems to run pretty fast, so things will show up on a refresh, or if you just wait a second or two (in my testing) before clicking on the link.  That seems like an inelegant solution to me, but not sure we can do anything about it? i mean, the ESN worker is asynchronous for reasons.

**Comment by rahaeli** [comment]
Can't be solved technically, but can be solved with user expectation management: additional note on the splash page, after the "view sent PM" link, saying: "If your message doesn't appear yet, please wait a few minutes and refresh the page."

**Comment by woggy** [comment]
Note added.
