### ISSUE TITLE
investigate BML::note_mod_time in /support/faq

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1272]
@afuna's comments in issue #1263:

BML::note_mod_time doesn't have to do with language; it takes the modification time of the FAQ and adds it to the headers so we can return a 304 Not Modified if relevant.

It does not appear we actually use it, because we never pass in the appropriate options. Could you open up a bug to investigate further BML::note_mod_time in /support/faq though?

I hear and obey.

**Comment by afuna** [comment]
Okay, so, basically:

BML::note_mod_time is used all over the place to detect whether the content / config / site skin / etc have changed. 

How this is all supposed to work:

* browser makes request, we send back header `Last-Modified: $timestamp_foo`
* next time browser visits that page, it includes header `If-Modified-Since: $timestamp_foo`
* if the latest modification time <= `$timestamp_foo` then we return HTTP_NOT_MODIFIED.

In the DW case, the BML module only returns the `Last-Modified` header if we set `$req->{want_last_modified}`. But we never seem to!

So I guess my question is: do we want to reimplement in non-BML context? Because we don't use this in the BML pages where it's currently implemented.

**Comment by rahaeli** [comment]
If we aren't using it and haven't been using it this whole time, and we haven't missed it, I think we can probably live without it.

**Comment by afuna** [comment]
Yeah. I’ve looked over it several times and I think I’ve convinced
myself I’m not just imagining that this isn’t actually used on the site.

**Comment by rahaeli** [comment]
Should we remove it from the places where it's implemented, or will it get picked up as we convert?

**Comment by afuna** [comment]
It’ll get picked up as we convert (and remove BML).


On Wed, Mar 4, 2015, at 03:20 PM, Denise Paolucci wrote:
> Should we remove it from the places where it's implemented, or will it
> get picked up as we convert?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1272#issuecomment-77272658
