### ISSUE TITLE
username misaligned under userpics in lastn view on communities

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1297]
I know for sure this is happening in ColorSide (see: http://synecdochic-decants.dreamwidth.org/ ) and Skittlish Dreams (see: http://dw-news.dreamwidth.org/ ) and I think it's happening in a few other layouts, but since I don't remember what they looked like before the push I can't say for sure: the poster username is no longer aligned under the poster's userpic, where previously it was.

Looking at source, I did notice that there's now a space in the line:

<span class="poster entry-poster ">

Could that be causing it?

**Comment by afuna** [comment]
Hmm, which line? I think that github cleaned it out.

**Comment by kareila** [comment]
`<span class="poster entry-poster ">`

Slack preserved it.

**Comment by afuna** [comment]
Thanks @kareila.

I switched to release-1.23 and tried recompiling the styles, and got things that look the same. I'm not sure what's going on because I'm not sure what I'm trying to fix.

The poster username not being beside the poster's userpic -- for colorside at least, that code has been there since 2011; that's not something we've changed recently. 

I'm going to try recompiling styles from release-1.22, maybe I'll see the difference there somehow.

**Comment by afuna** [comment]
Still the same.

I don't think the empty space has any difference (if you mean the one in the class attribute!). I'm at my wit's end figuring this out. Do we have any older installations I can look at? Screenshots / code?

**Comment by rahaeli** [comment]
Okay, I checked the (older) version of Colorside on my local dev machine and you're right, I was misremembering that one.

I'll try getting more info from the people who were complaining about it to me and check against the old version. Closing until then, sorry.
