### ISSUE TITLE
hovering over icons posted in comments/entries no longer triggers ctxpopup

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1313]
http://dw-maintenance.dreamwidth.org/67313.html?thread=2389745#cmt2389745

At least, I think that's what they're reporting!

**Comment by afuna** [comment]
Oops. I'll look into it! Probably the JS is not aware of what icon URLs actually look like.

**Comment by afuna** [comment]
Oh. I see, I got it the other way around. I thought the issue is that we were not doing contextualhover for system-generated icons, but I see that this is contextualhover not showing up for icons that are posted using the old-style URL.

The question I have is whether we want to support this or not!

**Comment by rahaeli** [comment]
It worked previously, so unless there's a good reason for it not to work now, we should support it. (The fact that people reported it as a bug means people are using it, at least!)
