### ISSUE TITLE
convert-to-points system does not distinguish between "hasn't been 30 days since last conversion" and "not enough time to convert"

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1340]
http://www.dreamwidth.org/shop/refundtopoints is supposed to not let you convert paid time to points in either of the following cases:

1. It's been less than 30 days since the last time you converted paid time to points.
2. You have fewer than 30 days of paid time on the account.

However, no matter which of the two conditions it's failing on, the error message is always /shop/refundtopoints.tt.toofew ("Sorry, you have less than 30 days of paid time on your account.") In condition 1, the error should be "Sorry, you've converted your paid time to points within the last 30 days. You won't be able to use this tool again until [date]."

**Comment by kareila** [comment]
I think I see what is happening here.  The error messages for both cases exist in refundtopoints.tt (the other case is /shop/refundtopoints.tt.toosoon) but they are being tested out of order.  The clauses for "NOT points" and "NOT can_refund" should be swapped so that the more specific error condition executes first.

Doing that will fix the wrong error being printed, but that leaves open the question of updating the .toosoon error message to include the relevant date.  Right now it just says "Sorry, you can only refund paid time once every thirty days."

**Comment by rahaeli** [comment]
Either way would be fine! If it's too much of a pain to add the date, just getting it to display the correct error message would be an improvement.
