### ISSUE TITLE
if given a proxy URL for an image, find entries the image it's proxying appear in

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1389]
I'll take "things I didn't think about for $1000", Alex: if someone hotlinks an image from an external website, that website's owner sees the proxy URL in their logs and takes offense at the use of their image and sends us a DMCA report using the proxy URL as the 'location of the infringing material', we need to, knowing only the proxy URL, be able to find the original entry the proxied image appears in.

If it *really* can't be done, I think we're just barely legally in the clear, for reasons that would take me a long time to explain, but those reasons really hard to explain to somebody and it would be really nice to save the effort.

**Comment by rahaeli** [comment]
(That was probably as clear as mud, so if you need me to give better examples, I can.)

**Comment by alierak** [comment]
I don't believe the website owner's logs would include anything of the kind; I think it would look to them as though the proxy itself requested the image with no Referer. But if it appears somewhere in a public entry, they'd be able to crawl the site and see the proxy URL that way, in which case they'd also know on what page they found it.

There's not a one-to-one mapping, though, and the proxy URL, once created, seems to be valid for use anywhere. If two people link to the same 'infringing material', you need to find both of them, and probably only a search function is going to be able to do that, unless you keep some kind of log of all the conversions of external URLs into proxy URLs.

Perhaps the proxy URL is going to have to include information about where it came from, the proxy is going to have to do a Referer check, etc.

**Comment by afuna** [comment]
So three suggested approaches.

Search: we send the raw entry text with the unproxied URLs, so we can't
use the existing search functionality. Tabling this unless the other two
are equally unfeasible.

Keep track of relationships: Stick into memcache the source entry every
time we convert a URL? Not sure I like this plan; it involves keeping
track of a lot of info for a just in case ( and if we schedule the
expiration to match that of the proxy image, we likely won't have the
info on hand when the DMCA, or whatever request comes in).

Proxy URL: including information about where its from -- tentatively, I
think that it would be possible to encode in the proxy URL the viewed
entry information as additional arguments, and strip them out from
consideration in the proxy (so if we have the same image referred from
multiple entries, it still only downloads it once).

**Comment by alierak** [comment]
It also occurs to me that we really have to do something that affects validity of the proxy URL. If the DMCA report contains a proxy URL, and the proxy URL continues to work, then we haven't actually taken down the infringing material and anyone can verify that it's still there by visiting the proxy URL and causing it to be cached again. Someone could embed the image on a completely unrelated site using the proxy URL, so that we appear to be hosting it. If we can't give the proxy a blacklist, then Referer checking is probably the next best thing, but that requires info in the proxy URL to check against.

**Comment by rahaeli** [comment]
I think the proxy URL step might be the best solution there.

**Comment by afuna** [comment]
Okay, so this still requires a lot of manual work, but based on the discussion above, this changes the URLS from:

    https://proxy.dw.net/TOKEN/URL

to:

    https://proxy.dw.net/TOKEN/journalid-ditemid/URL

One thing of note: I decided to go with ignoring the journalid-ditemid part of the URL instead of signing it (that is, treating it as additional information) because I'm not sure of the implications re: caching if we have the same file but used in multiple entries.

The pull request is only for identifying entries; it doesn't do anything wrt expiring in the proxy itself.

**Comment by rahaeli** [comment]
Love it, that'll work just fine. <3
