### ISSUE TITLE
Remove extra whitespace below icons caused by HTML5

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dw-free#1391]
Layouts directly affected:
abstractia
bases
databases
modular
motion
patsy
skittlish dreams
sunday morning
transmogrified

But I'm going to see if putting something in TR to fix it doesn't bork the totally-okay ones, so we don't have this problem going forward with new styles.

**Comment by momijizukamori** [comment]
claiming

**Comment by afuna** [comment]
Okay!  I'd definitely like to know what this fix entails :)

**Comment by momijizukamori** [comment]
The same display:block thing I did to fix it in Planet Caravan :) Because
we *do* basically treat userpics as block elements rather than inline ones.

**Comment by afuna** [comment]
Aha gotcha. For some reason I thought there was something more
complicated involving line heights and `br`s. But now that you remind me
that makes sense *g*


On Thu, May 21, 2015, at 01:44 PM, momijizukamori wrote:
> The same display:block thing I did to fix it in Planet Caravan
> :) Because
>
we *do* basically treat userpics as block elements rather than
inline ones.
>
>
On Thu, May 21, 2015 at 12:00 PM, Afuna
<notifications@github.com> wrote:
>
>
> Okay! I'd definitely like to know what this fix entails :)
>
>
>
>
>
>
>
>
>
> > On May 20, 2015, at 20:11, momijizukamori <notifications@github.com>
>
> wrote:
>
> >
>
> > Layouts directly affected:
>
> > abstractia
>
> > bases
>
> > databases
>
> > modular
>
> > motion
>
> > patsy
>
> > skittlish dreams
>
> > sunday morning
>
> > transmogrified
>
> >
>
> > But I'm going to see if putting something in TR to fix it
> > doesn't bork
>
> the totally-okay ones, so we don't have this problem going forward
> with new
>
> styles.
>
> >
>
> > —
>
> > Reply to this email directly or view it on GitHub.
>
> >
>
>
>
> —
>
> Reply to this email directly or view it on GitHub
>
> <https://github.com/dreamwidth/dw-free/issues/1391#issuecomment-104331860>
>
> .
>
>
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1391#issuecomment-104415653
