### ISSUE TITLE
entered text lost when switching from Reading Page QuickReply to full comment form

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1484]
If you click on a 'reply' link on your reading page and trigger a QuickerReply form, but decide you want more options and hit the 'more options' button after entering text, the text you've already entered is lost. We should preserve anything you've already entered and pre-fill it on the More Options form instead.

**Comment by kareila** [comment]
Ha, that bit me just yesterday and I thought maybe it was my browser misbehaving.

**Comment by kaberett** [comment]
Is this suitable for beginners?

**Comment by rahaeli** [comment]
A little more complex than the average thing that gets tagged for beginners, but not outside the reach of somebody who's particularly motivated, I'd say. (So, probably safer to not tag.)

**Comment by kaberett** [comment]
In which case I claim it. :-p

**Comment by kaberett** [comment]
... okay, I've just got around to poking this some more and behaviour is as intended on 'hacks for me (in that entering some text in the QuickerReply form on my reading page, then hitting "More Options", takes me to the entry page with ?mode=reply <i>and the text I had entered</i>). It is however failing to work (dropping text on the floor) per descriptions in this issue on production.

????, yea verily.

On my 'hack I'm going from Funky Circles to Negatives (in style terms); in production I'm going from Sunday Morning to Nouveau Oleanders.

**Comment by wychwoodx** [comment]
I'm getting the same effect as kaberett - on my hack, the text is carried over from the QuickerReply form to the ?mode=reply page, but when I tested on production, it vanished.

**Comment by kareila** [comment]
@alierak has poked this a bit and says that it has something to do with a POST request being converted to a GET request after fetching a domain session cookie (because it is switching context from the user's domain to the domain of the journal being viewed).  If you visit the entry page first, and then try the QR from your reading page, it doesn't need to fetch the domain session cookie and the form text is preserved.  That being the case, the likely reason for it not showing up in development is that the developer has just looked at the journal for whatever test user they are sock puppeting, so the cookie is already present.

**Comment by rahaeli** [comment]
Hmmmm. In which case this may be more complex.

**Comment by kareila** [comment]
We have an idea for a workaround but we haven't coded it up to test yet.

@kaberett, do you mind if I snag this from you?

**Comment by kaberett** [comment]
No, please go ahead!

**Comment by kareila** [comment]
Thanks!  Wish us luck...

**Comment by kaberett** [comment]
... and all the joy of it. I'll send someone after you if I don't hear from you in a fortnight ;)

**Comment by kareila** [comment]
The first thing we tried was adding some JS in the onclick handler to request a cookie for the other domain, but the request was blocked by the server due to cross-site scripting concerns.

@alierak pointed out that if we can instead somehow generate a request in the background for content being served from the other domain when the link is clicked, that should be enough to set the cookie. He suggested using a 1x1 pixel gif for that purpose, unless someone else has a better idea?

**Comment by kaberett** [comment]
(Another report: https://www.dreamwidth.org/support/see_request?id=36539)

**Comment by kaberett** [comment]
https://www.dreamwidth.org/support/see_request?id=38274

**Comment by azurelunatic** [comment]
Quoting Nick: 
Newly exposed by switching the Post Comment & More Options buttons.

**Comment by nfagerlund** [comment]
Next reply form revision should help a bit: 

![screenshot of next reply form](https://roadrunnertwice.dreamwidth.org/file/26794.png)

- "More options" can't be confused with "post comment" anymore.
- Also, it's at the top of the form, so if you're going to click it on purpose, that encourages you to do so _before_ typing anything.

**Comment by nfagerlund** [comment]
Okay, so I poked at this and I think @alierak's idea of fetching a 1x1 gif is pretty promising! I got it working by reaching out and grabbing a stylesheet instead! 🙌🏼 (Had to be a stylesheet because I couldn't find any images that lived on a user domain aside from favicon.ico, which has a weird special case treatment in LiveJournal.pm and thus won't work for this purpose. So we'll need to add a dedicated image for this purpose and make sure it always goes through the normal apache request handling.) 

Here's the missing piece: the easiest way to do this requires the modern `fetch()` API, so [we're not fixing this for IE11](https://caniuse.com/#search=fetch).

Anyway, in the JS handler for "more options," we need to do something like this:

```javascript
fetch('http://sheworks4themoney.rr-thrice.hack.dreamwidth.net/res/32/stylesheet?1567191564', // change to image url later
  {mode: 'no-cors', credentials: 'include}
).then(res => { 
  // all the stuff that's currently in the "more options" submit handler
  // also don't actually do anything with the response object, it's useless because 'no-cors'.
});
```

That `'no-cors'` bit makes it so the browser will let us complete the request and have our domain session cookie set, without us having to go in and deal with actually setting CORS headers. An alternate approach would be to designate that magic 1x1 gif as special, and do a real dot-the-I/cross-the-T CORS request, but cheating is probably the move here because we don't actually care about the content of what we're requesting. (And that's the bit that requires fetch: XHR can do real CORS, but it doesn't have a way to disclaim interest in the content, so you can't cheat like that.)

**Comment by nfagerlund** [comment]
Actually, `robots.txt` is probably easier to work with than adding a special 1x1 image where we need to remember why it's important for the rest of time.

**Comment by nfagerlund** [comment]
Whipped up a patch, and this totally works.
