### ISSUE TITLE
antispam: make spam report sortable

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1522]
Currently, spam reports sort by date reported. 
I would like spam reports to also be sortable by date left, for troubleshooting purposes. 

Specific use case: say someone's email is compromised and a spammer gets into it. A site admin resets the secret address and notifies the user. Meanwhile, only one of the communities that the user accidentally spammed has reported in. Two months later, other community admins notice and spamdelete. I want to be able to sort by time of date left to make sure that all of it was left before the most recent secret address reset.

**Comment by kaberett** [comment]
(Is this suitable for beginners?)

**Comment by kareila** [comment]
I would say no, because it's a bit more involved than our usual bait bugs.

I was thinking of working on this myself, but I need @azurelunatic to clarify: the page you want to be resortable is the one that lists the details of every report, yes? Not the tabulated summaries?

(Also if I work on this, I will probably de-BML it as well.)

**Comment by azurelunatic** [comment]
Correct, the page with the details of each spammer/alleged spammer.

**Comment by kareila** [comment]
Thanks for the clarification!  That's what I thought but I wanted to be sure.
