### ISSUE TITLE
Remove Select modification level for answer from faqedit

### ISSUE THREAD

**Issue by zarhooie** [dreamwidth/dw-free#1524]
The modification level drop down is useless for us. The only use I can possibly see is for forked projects who do use translators. Let's look into removing it.

**Comment by rahaeli** [comment]
Yeah, unless @zorkian has an objection I say kill it.

There's also a severity on /admin/translate but I think that's more baked into the system. We should be ok with just removing the dropdown on the faqedit page. (Might also require setting a default severity for the change, because the translation system does expect a severity and it might result in weirdness if it's not there, but it would be ok to just set everything to no-notify behind the scenes.)

Fun fact: The translation system has four severities. The FAQ edit page has three severities. They're named different things. Nobody ever had any idea how they mapped onto each other. Ia, ia, translation system fth'a'gn, etc.

**Comment by zarhooie** [comment]
![tumblr_mdygm3uten1rjdfzto1_400](https://cloud.githubusercontent.com/assets/4575445/9148115/441a884e-3d38-11e5-819b-03f52ee7fac8.gif)
NGL, this is what I think of whenever we talk about the translation system. Except the lights are on fire, and the blades are made of candy corn.

**Comment by rahaeli** [comment]
And the spec for it was originally to build a refrigerator instead.

**Comment by zarhooie** [comment]
And the last time someone ducked into the utility room to flip the breaker for maintenance, they disappeared, leaving only the faint scent of Fresh Rain dryer sheets behind. They showed up in Belize a year later with shock white hair, and a Canadian accent.

**Comment by zorkian** [comment]
purge it with fire.

**Comment by me-and** [comment]
Eh, I was just playing with the FAQ system anyway, so I might as well claim this.

**Comment by me-and** [comment]
(Although, unless anyone has any objection, if the desire is to burn anything relating to the translation system with fire, I might see how difficult it is to remove the field entirely, rather than just pretending it isn't there and filling it in behind the scenes.)

**Comment by zarhooie** [comment]
Knowing the translation system, prodding at it in any way might change all the site text to Greek. (But hey, sounds good to me. Probably get a sign-off from The Tallest, though.)

**Comment by rahaeli** [comment]
I have no objections to getting rid of severity more widely, but I don't think it will be a simple fix.

**Comment by rahaeli** [comment]
If the site suddenly starts talking in Klingon, y'all are on your own. I'm just sayin'.

**Comment by kareila** [comment]
Hey @me-and - are you still interested in submitting the fix for this, or should I use mine?

**Comment by me-and** [comment]
Oh, if you have a fix, go for it! I haven't managed to code one up yet.

**Comment by kareila** [comment]
I'll submit my simple fix using html_hidden, and you can open a separate issue for removing the column from the database if you're still interested in investigating that. :bomb:

**Comment by kareila** [comment]
WTF iPad menu jumping like a jumping thing. Sorry about the wacky reassignments there.
