### ISSUE TITLE
DW-hosted image permissions interact poorly with custom access filters

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1527]
Images set as visible to "Access List", when included in a post to a custom access filter, are visible only to the post owner and not to people in the access filter. Images set viewable to Everyone (Public) <i>are</i> visible when included in a post to a custom access filter. ("Access List" images included in posts visible to the entire access list are visible; I haven't tested whether the same applies given a default access filter, because I haven't got one.)

... as far as I can tell, having poked at it a little. I think it is fairly obviously the case that an image not being viewable in a custom-access-filtered post if it's set visible to Access List, but that it *is* visible if it's set to Everyone, is not ideal? In that custom access filters are a subset of the entire access list (in much the same way that the access list is a subset of "everyone"), so...

**Comment by kaberett** [comment]
I'm also seeing reports of weird shit happening when people have their default entry level set to access-locked and try to upload images set to "public" - hanging forever, no error message, etc. (http://kriegor.dreamwidth.org/46106.html)

**Comment by kareila** [comment]
These are two separate issues requiring two different fixes.

Here are my initial findings:

The first problem seems to be in `visible_to` in DW::Media::Base.  It looks like there's a bug in the usemask checking code, where trustmask and allowmask are expected to match but don't.  I'm not sure exactly what is happening here, though, since the access level of the post doesn't factor into it, only the access level of the image itself and the trust relationship of the two users.  And it looks like the /file/edit page doesn't support custom access groups for images, although the API does.

As for the second problem, looking at DW::Controller::API::Media, it would appear that /file/new in this context doesn't support security selection at all - it always uses the user's minimum security, period, which again, doesn't allow the selection of custom access groups. And in `upload_media` in DW/Media.pm, this results in allowmask = 0 in all cases.  I'm pretty sure this is a bug (the /file/edit page makes sure allowmask = 1 if we've requested access-only) but I would have to investigate further to see if changing this alleviates the reported behavior.

**Comment by kareila** [comment]
I just put in a PR with fixes from digging into the second issue. With these in place, I wasn't able to reproduce the first issue when using /file/edit to tweak permissions.  I would encourage anyone continuing to see odd behavior to set any misbehaving images to public, then reset to access-only, which should clear up any bad allowmask values.
