### ISSUE TITLE
Error in log when posting a comment with a CAPTCHA

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#1604]
This bug does not appear to affect the functioning of the site.
However, on my 'hack, when I post a comment that requires me to pass a CAPTCHA, and I do pass it, then it posts fine but there's an error in the log:

`Use of uninitialized value in concatenation (.) or string at /dreamhack/home/8374-swaldman/dw/cgi-bin/DW/Captcha.pm line 213.`

It happens when posting as anon and when posting as a logged-in user.
Only tested with text CAPTCHA.

**Comment by kareila** [comment]
I see these uninitialized value warnings all the time - they're just an annoyance, but taking the time to clean them up is appreciated.  The usual fix is to make sure you concatenate an empty string instead of the undefined variable, or else use a conditional to only apply the variable if it has a value.

**Comment by me-and** [comment]
Hm. This one doesn't look quite so utterly trivial, at least to my not-very-familiar-with-Perl eyes: [the relevant line](https://github.com/dreamwidth/dw-free/blob/develop/cgi-bin/DW/Captcha.pm#L213) is `my $stat_tags = [ (ref $self)->name, "page:" . $self->page ]; I *think* the error is being caused by `$self->page` not having been initialized, but it's not obvious (at least to me) where that value should be initialized.

**Comment by kareila** [comment]
Well, that line is in the `validate` method, and if it's happening when posting a comment, then it's almost certainly the one used in LJ/Talk.pm, at line 3337:
```
return $err->( $captcha_error ) unless $captcha->validate( err_ref => \$captcha_error );
```
If you look a few lines up from there, you can see that the captcha object was created with page set to `undef`. So the question to ask next is: do we want to change the behavior of the code by passing in a different argument when creating the captcha, or do we want to just do a simple fix where the error is happening and print an empty string when the page is undefined?  Since it's a logging call for the Stats module, which I believe only cares about traffic to site pages and not journal pages, the latter is probably the correct answer here.  Something like:
```
my $pageref = $self->page // '';
my $stat_tags = [ (ref $self)->name, "page:$pageref" ];
```

**Comment by cesy** [comment]
Claim
