### ISSUE TITLE
Page title "ext_1 in your circle" when circling an OpenID user

### ISSUE THREAD

**Issue by chrisboyle** [dreamwidth/dw-free#1608]
The title of `/circle/ext_1/edit` is "ext_1 in your circle". There is a correct title in the body of the page: "joeblogs.example.org in your circle".

**Comment by me-and** [comment]
The problem here is in `individual-edit.tt`; specifically this code:

```
[%- sections.windowtitle = ".title" | ml( user => u.username ) -%]
[%- sections.title = '.title' | ml ( user => u.ljuser_display( head_size = "24x24" ) ) -%]
```

The call to `u.ljuser_display` is producing the sensible name, but also with an icon and link formatting and so forth; the `u.username` field is the one that's currently `ext_{number}` and should be something akin to the output of `u.ljuser_display`.

**Comment by kareila** [comment]
I think `u.display_name` is the method to use instead of `u.username`.
