### ISSUE TITLE
parsefeed-atom-types.t test fails

### ISSUE THREAD

**Issue by cesy** [dreamwidth/dw-free#1637]
It's not clear whether that's because the atom feed itself is broken, or the test is incorrect.

The comments say this:
```perl
# When type="html", the contents should be escaped HTML
# The correct result is the content with one level of escaping removed
# When type="text", the contents are escaped plain text
# Since LiveJournal expects HTML in the subject field, parsefeed should
# be returning the text with HTML escaping applied.
```

The HTML ones pass; the text ones don't.

The text ones are:
```perl
is($testtitle->(qq{<title type="text"><![CDATA[<title>]]></title>}), "&lt;title&gt;", "Title: Text + CDATA");
is($testtitle->(qq{<title type="text">&lt;title></title>}), "&lt;title&gt;", "Title: Text + Entity");
is($testtitle->(qq{<title type="text">&#60;title></title>}), "&lt;title&gt;", "Title: Text + Numeric character references");
```

This passes:
```perl
is($testtitle->(qq{<title type="text"><![CDATA[<title>]]></title>}), "<title>", "Title: Text + CDATA");
is($testtitle->(qq{<title type="text">&lt;title></title>}), "<title>", "Title: Text + Entity");
is($testtitle->(qq{<title type="text">&#60;title></title>}), "<title>", "Title: Text + Numeric character references");
```
But is that actually the behaviour we want in the feed?

The XHTML ones appear to have a similar problem.

**Comment by kareila** [comment]
The current test plan is unchanged since the LJ fork, and has been marked as broken since Sep 2009.  At this point it probably makes the most sense in the absence of arguments to the contrary to say that the current behavior is desired, and update the tests to pass accordingly.  I have to think that if the escaping we use in our Atom feeds were actually broken, we would have heard at least some complaints about it within the past six years.

**Comment by zorkian** [comment]
+1 to "been six years, probably fine".

**Comment by rahaeli** [comment]
It's funny how often the answer is "well, if nobody's noticed it's a problem in six years, it's probably okay".
