### ISSUE TITLE
FAQs 37, 38 and 39 are uncategorised

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1758]
This is occasionally unhelpful, per http://www.dreamwidth.org/support/see_request?id=33236 -- it would be nice to be able to link directly to the FAQs, rather than having to say "Part 3, linked from FAQ 36".

If they're going to be put in a category, it should probably be Guides.

**Comment by kaberett** [comment]
(@rahaeli -- think this one's gotta be youuuu.)

**Comment by rahaeli** [comment]
Eh. I can see the argument for doing this, but when we were doing the initial documentation, we specifically didn't link the sub-pages of the Guides in the main/full FAQ list because the main FAQ list is hella long (and has only gotten longer) and the individual pages of the guides don't really have informative titles that would be helpful to somebody looking at the full FAQ list. (I mean, you wouldn't click on "How do I protect my privacy on Dreamwidth? (Part 1)" if you saw it on a list thinking "that will answer my question!") And changing the title would lose the cohesion of "these are all part of the same overall document, just broken up into parts for easier reading".

I think this is a case where the needs of the use case of "someone looking at the full FAQ list" (way more common) is going to have to win over the use case of "support vol wanting to reference an individual part of a guide" -- people can reference the top-level guide and say "part three (or whatever) has some information that might be useful for you".

(I thought about changing this to "let vols reference uncategorized FAQs in an answer", but there are a hell of a lot of uncategorized FAQs and most of them are "this FAQ no longer exists"; too easy to misclick, and too hard to find the one you want in the list.)

**Comment by rahaeli** [comment]
PS: apropos of nothing, but you can kick "I think somebody broke into my account" over to ToS in the future -- we can look into them more with various admin tools and give the user more specific advice to their actual situation.
