### ISSUE TITLE
The "ip" column in the userlog table should be widened to accommodate IPv6 addresses

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1818]
It is currently only 15 characters wide.  IPv6 addresses can be up to 45 characters, per discussion in #1393.  I'm seeing some IP mismatch errors in the logs from SecurityAttributeChanged.pm due to the truncation.

**Comment by kareila** [comment]
Still seeing these errors in logs:

`The event (uid=1212584, extra='old=V&new=D', 'new=D&old=V', logtime=1493613726) was found in log, but with wrong ip address (2601:0081:4203:, but not 2601:0081:4203:ce70:7521:065d:6f7b:21ca) at /home/dw/production/cgi-bin/LJ/Event/SecurityAttributeChanged.pm line 56.`

Any takers?

**Comment by pauamma** [comment]
So what should be done to test that this bug is fixed, other than checking (using the mysql client) that the column was indeed widened? It looks like dreamhacks only have IPv4 addresses, so I'm not sure how to get an IPv6 address into userlog. (I think that if I could do that, the extra test would be to delete and undelete an account.)

**Comment by zorkian** [comment]
I'm OK with deploying it and seeing if userlog is successfully getting IPv6 entries aftwards.
