### ISSUE TITLE
Comment via email silently fails to give IP information to ip-tracking journal owners (and probably community admins too)

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1831]
Expected: When IP logging for all users is turned on, all comments should show an IP address or other similar identifier. 
Actual: When comment (at least from yourself) is left in a journal via email, IP address is not displayed when viewing the entry. Instead, a blank is displayed where the IP address ought to be. 

Is it useful to collect the IP that the email is being sent from? 
If it is already being collected, are there any objections to showing it to someone who is logging IPs? 
(If there is a potential privacy issue with IPs being collected unwarned, can the warning be put into the comment notification in the instructions to reply via email?) 
If collecting the IP or showing it is a problem, could some other message be displayed to the journal owner so it's not a blank mystery? 

dw-free/cgi-bin/DW/EmailPost/Comment.pm and dw-free/cgi-bin/LJ/Talk.pm may be helpful in resolving this.

**Comment by kareila** [comment]
I don't think the information is being collected, and even if we wanted to, I'm not sure collecting e.g. the IP address of the user's SMTP server would be considered uniquely identifying...

**Comment by azurelunatic** [comment]
It would effectively be naming their email provider in some cases; is that
something that should be done?

**Comment by rahaeli** [comment]
No on capturing IP addresses via comments-by-email, for a bunch of reasons:

a) Not all mail servers add an IP address that the mail was sent from to the headers of outgoing emails.
b) The ones that do don't do it consistently: the header is named something different from every mail server that does it.
c) Mail is not a 1:1 server-to-server relationship: emails can go through loooooots of servers to get to their final destination. All well-behaved servers that touch an email add a Received: header, often with IP, but that's not the IP of the person who sent the email: it's the IP of the intermediate SMTP server.
d) We could get (as Jen points out) the IP address of the SMTP server that handed us the email, but again, that's not the user's IP address, and it's not even guaranteed to be the user's SMTP server (which is different than their email provider; I use a SMTP server that I don't get mail at, for instance).
e) mail headers are not a trustworthy source of info and can be easily faked; I could hand DW's servers an email that said I was president@whitehouse.gov with an IP of the White House, and they would happily accept it. (With appropriate caveats that some servers have strict checking, but that's a relatively small part of the internet.)

All of that's a moot point, though, because:

f) it is impossible to email in a comment without having gotten a comment email in the first place, and it's impossible to email in a comment anonymously: the only way to add a comment by email is by replying to a coment reply email that went to a DW account, and you can only reply as that account. So, anyone who replies to a comment by email is guaranteed "identified" (FSVO "identified" that means "is a unique DW account"), and (in the event of the comments being unwanted) can be banned. IP logging really is an anti-abuse measure against anon comments, and is less valuable for logged-in users.

I could see fit to displaying "IP not available" or "via email" or something just for consistency's sake, but I don't think it would be worth the time spent on it, honestly -- more just something to note for if someone writes in and asks about it.
