### ISSUE TITLE
suggested improvement for /admin/priv: include packages in dropdown

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1841]
So now that I'm in the priv-granting business, I found myself looking around at the differences between the /admin/priv page vs. what's available on the console.  The thing that immediately jumped out at me is that the console supports the creation and granting of "packages" of privs, which are not listed in the dropdown menu on the /admin/priv page.  I suggest including them at the top of that menu, prefaced with the # symbol as on the console to avoid any confusion.

(Required reading: the console commands for 'priv' and 'priv_package' and the page source for /admin/priv/index, which is sadly still a BML file.)

**Comment by rahaeli** [comment]
Background on this: Priv packages were something we came up with on LJ (where support privs were granted pretty frequently and where the ToS team had several 'classes' per year that all needed a bunch of privs) to make my life easier, so that instead of having to grant 15 privs individually (and risk forgetting one) I could just grant the priv package. It does require setup (creating what privs go in the package) and I don't think we've ever defined packages on DW, mostly because priv packages had just recently been added when I quat LJ and I had mostly forgotten about them up until now :P

Adding them to /admin/priv is a good idea, though! And I should probably get around to setting some up for DW.

**Comment by kareila** [comment]
@zarhooie created one for basic support privs, which is good because dear god the number of support privs.

**Comment by rahaeli** [comment]
Sweet, I didn't realize that existed. \o/ (I actually have the console commands for granting the support privs stuck into muscle memory from having done them so many times...)

**Comment by pauamma** [comment]
The main difficulty on this is filtering out packages the logged-in user doesn't have all admin powers required to grant. Or, perhaps more easily, there should just be an error message if the selected package includes privs the user doesn't have admin for, with the other privs granted anyway. What do you think?

**Comment by zorkian** [comment]
Privilege granting is pretty rare and only for power users, so I'm okay
showing every package and throwing an error if it fails when they try
to grant it. Bad UX, but for the 15 people who can grant permissions
it's okay.
