### ISSUE TITLE
Save descriptions can give error message when there are no descriptions

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1855]
Uploaded several pics via drag and drop; clicked on save descriptions because I though I had to save and got this:

`Unable to save: Need a user and mediaid key at /home/dw/production/cgi-bin/DW/Media.pm line 34. DW::Media::new('DW::Media', 'user', 'LJ::User=HASH(0x7fcfac4b6b00)', 'mediaid', 0) called at /home/dw/production/cgi-bin/DW/Controller/API/Media.pm line 127 DW::Controller::API::Media::file_edit_handler('DW::Routing::CallInfo=HASH(0x7fcfac6dd818)') called at /home/dw/production/cgi-bin/DW/Routing/CallInfo.pm line 82 DW::Routing::CallInfo::call('DW::Routing::CallInfo=HASH(0x7fcfac6dd818)') called at /home/dw/production/cgi-bin/DW/Routing.pm line 227 eval {...} called at /home/dw/production/cgi-bin/DW/Routing.pm line 227 DW::Routing::_call_hash('Apache2::RequestRec=SCALAR(0x7fcfac20c028)') called at -e line 0 eval {...} called at -e line 0`

Tried it again and got a nice message this time.

**Comment by kareila** [comment]
Looks like that's the expected behavior for a code path that isn't supposed to happen (mediaid of zero), which is why it prints debugging info?  I suspect some bit of JS code failed to execute the first time.

The file_edit_handler is designed to return an API error if the call to DW::Media->new fails, but DW::Media->new is preempting that with a confess statement.  Simplest fix would be to add an additional check for a non-zero mediaid argument before making the call to DW::Media->new at cgi-bin/DW/Controller/API/Media.pm line 127.

**Comment by kareila** [comment]
After digging around in DW::Media->new for #1928 and realizing all the different ways it can fail, I suggest instead a similar fix to what I used there, which was to wrap the DW::Media->new call in an eval statement to trap any fatal errors that would preempt the API error return.

**Comment by kaberett** [comment]
yo @rshatch, I've put this in the beginners' bugs masterlist but if it's relevant to your current work...

**Comment by kareila** [comment]
I spotted this again in the production logs and the bogus mediaid being passed in is the string "null", not zero or undef. Thanks Javascript.
