### ISSUE TITLE
CSS in Tabula Rasa overrides height attribute in IMG tag

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1856]
Request: https://www.dreamwidth.org/support/see_request?id=29575

Culprit is:

`.entry-content img, .comment-content img {
     height: auto;
     max-width: 100%;
}`

This certainly has a purpose although I can't remember which one. Make sure images don't overlap the container? Aren't cut off?

**Comment by ninetyd** [comment]
Oh and this could be in other styles too. Haven't checked.

**Comment by ninetyd** [comment]
May have something to do with responsive design: http://webdesignerwall.com/tutorials/5-useful-css-tricks-for-responsive-design

**Comment by kareila** [comment]
Yes, it looks like this was done as part of #841 to enable responsive resizing of images in mobile-friendly journal views.  That's where the max-width came in, and presumably the height needed to also be specified to auto-scale in order to match the modified width.

Google points to this as a potential solution: http://bit.ly/2bU3LE3

**Comment by kareila** [comment]
Also possibly affected: Abstractia, Bases, Blanket, Brittle, Drifting, Easyread, Negatives, Skittlish Dreams, Summertime.

**Comment by momijizukamori** [comment]
We've updated the code handling image resizing in entries and comments, so I'm going to close this as any current issues are most likely something exciting and new.
