### ISSUE TITLE
Most-requested file-manager tweaks for roll-out

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1936]
http://dw-dev.dreamwidth.org/194532.html

Most changes want to happen to https://www.dreamwidth.org/file/edit. Requested UI changes are:
* _paginate_ (so that the page remains useful for people who've uploaded a lot of files); Azz's preference is to have the first page be the first images uploaded, the last page be the most recent images uploaded, and the default landing place to be the last page
* option to display in grid instead of list?
* if dates are recorded anywhere, display date-of-upload
* show file size and height*width of full image
* provide image title and description (and ability to edit/save edits)
* provide the HTML for embedding an image
* bare bone link to your full-size image or simple HMTL with IMG instead of FIGURE/A etc (req'd by 90d)
* provide options for embedding a range of preview sizes of image (radio buttons?)
* if you've never uploaded anything, visiting /file/edit says "Here are all the files you've uploaded from mobile." (i) this should say "You haven't uploaded anything" with a link to /file/new; (ii) if users HAVE uploaded files, the message should read "Here are all the files you've uploaded."

Navigation:
* Organize --> Manage Files
* have internal links between the subpages (/file, /file/new, /file/edit

Features (stretch goals!):
* allow user-set preview sizes
* allow users to rename images
* allow users to sort images according to... criteria?
* user-friendly error messages
* allow tags/folders/etc
* a thumbnail gallery

Needs docs:
* supported image types
* max size (if any)
* ... an entire FAQ

**Comment by kaberett** [comment]
yo @momijizukamori, here's a bullet-point list! I will handle docs stuff if you can chuck me information. <3

**Comment by azurelunatic** [comment]
There's a thumbnail/preview re-sizer already attached, and it's a matter of specifying /###x###/ in the thingy, where ### are both any of the possible dimensions that the re-sizer will handle. So a pickybutton for which to show might well be a UI component.

**Comment by rshatch** [comment]
claiming!

**Comment by rahaeli** [comment]
Adding something that was in the suggestions queue that I didn't bother sending through for discussion: there should be links from /file/edit to /file/new and vice versa.

**Comment by rshatch** [comment]
Okay, a few notes as I poke at this - first off, we don't appear to save upload time, though given we have to modify the database schema for title and description, this may be a thing that can be added (though it wouldn't be populated for stuff already uploaded) - @zorkian, any thoughts on that?

Second, we should probably have a non-JS fallback for the upload page, which currently just falls over entirely if JS is turned off. That said, though,  the easiest way to implement a size-picker is with JS, and I'm not sure that functionality is important enough to justify the amount of extra work necessary to make it work without JS. The field would still be there with a reasonable default-size thumbnail link either way, just with JS on you'd be able to pick one of the sizes other than the default.

**Comment by rshatch** [comment]
Also, I'm trying to decide what information should be available in a grid view (as opposed to a list-view, which would show all of it). I'm inclined to say title or filename, dimensions, and a default thumbnail embed link? And then the grid element could link to a full-size view page with all the information.

**Comment by rahaeli** [comment]
I am OK with size picking not working without JS!

Grid view, hrm. Title, description, upload date, dimensions, tags (when we have tags)? IDK.

**Comment by rshatch** [comment]
I'm thinking description might end up too long and/or too variable in length for grid view, unfortunately - even title could be iffy.

**Comment by zorkian** [comment]
We don't need non-JS fallback. It's 2017 and we're about to turn on SSL-everywhere which is going to preclude really old, crufty browsers. If someone wants to post an image without JS, they can email it in (since we support post-by-email).

We should also add upload-date to the schema. Pretty easy and definitely useful information.

**Comment by azurelunatic** [comment]
For this case I think you're right, but I will generally note that even in
2017 some screen readers are still pretty old and crufty.

**Comment by zorkian** [comment]
Accessibility is absolutely a goal -- and one that can be obtained with JavaScript. We may decide that the easiest way to provide an accessible experience is to make a no-JS mode for a page, but let's frame the goal as 'make this accessible' rather than 'make this work w/o JS'. Does that make sense?

**Comment by azurelunatic** [comment]
Makes sense!

**Comment by rshatch** [comment]
Valid! I think in the past we had a 'should work without JS on' rule? Or strongly suggested guideline. I'm also always a little hesitant about 'all JS all the time' because even my fairly modern laptops sometimes encounter JS sites that are really unresponsive/make my whole system lag. I don't think this runs that danger, though :)

That said, do we have any idea of how acccessible the current interface is? That's not a thing I'm set up to test, unfortunately.

**Comment by kaberett** [comment]
@rshatch AUGH I'm really sorry, I forgot to include "a success message on successful upload" to the Most Wanted UI Features...

**Comment by rshatch** [comment]
@kaberett no worries! I will make a note of it for when I go poking around in the JS that makes up the uploader (because yeah, not totally obvious). Also, it turns out we already have DB-stuff defined for three props - title, alttext, and description. As such, I propose the following info shown in each view:

Grid view
-small thumbnail
-title
-file size
-dimensions
-embed-thumbnail field (with dropdown if JS is on)

List View
-all of the above
-embed-fullsize field
-alt text

Single Item View
-all fields

And then call 'alttext' 'Short Description' on the upload and edit pages, with the hope that with that name + it being shown as normal text in list view people will actually fill it out?
