### ISSUE TITLE
we should determine and enforce limits for media hosting

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1940]
Now that the file upload area is being more actively used and developed, we should make sure we have quotas in place for the different account types, and make sure they are documented.

**Comment by rahaeli** [comment]
hmm, good question. Having checked LJ, their current limits are:

Basic & Plus users: 1 GB.
Paid users: 2 GB (expandable to 10 GB through the shop.)
Permanent accounts: 15 GB.

That's probably a bit large for us, especially at first, so what about:

Free: 500MB
Paid: 1GB
Premium Paid/Seed: 2GB

Of course I will defer to @zorkian and @alierak on this, though!

**Comment by zorkian** [comment]
Standard S3 pricing is 2.3 cents per GB/month. We could possibly use the
infrequent access mode which drops that to half the price, but we should
figure on worst case of the above. Do we want to guess how many people
might use the functionality and how much of their quota they'll use?


Also, we should think about situations where someone just creates N free
accounts to store images on them. Is that a thing we should care
anything about?


I'm overall not _that_ worried since I believe we don't allow hot-
linking of images, so we aren't going to be a hosting service for people
posting images off-Dreamwidth.

**Comment by rahaeli** [comment]
> Do we want to guess how many people
> might use the functionality and how much of their quota they'll use?

Yeah, that's the problem I'm having: not having a good guess about what percentage of people will use it. Hmmmmmm.

I guess let's start with 500MB for everyone, watch for a month and see how many people use it/how much space they use and re-evaluate after that?

> Also, we should think about situations where someone just creates N free
> accounts to store images on them. Is that a thing we should care
> anything about?

I guess if it happens we can address it under ToS XI/11 (making excessive use of the service). But we should make absolutely sure that we don't allow remote loading of images!

**Comment by kareila** [comment]
Uhhhh, I don't see anything preventing hotlinking... we do a security level check but not a referrer check.
