### ISSUE TITLE
receipt not sent to buyer when gift is made

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1950]
Realized today this bug never made it over from Bugzilla:  if you buy a gift of paid time for someone, the person you bought for gets the "your account has been upgraded" email, but the person who pays doesn't get an emailed receipt even though the message tells them they do. They should get a copy of the receipt (like what's displayed on https://www.dreamwidth.org/shop/history).

**Comment by kareila** [comment]
Hmm, are you sure this is still the case?

I've been studying the code and it looks to me like the recipient gets emailed at the point where the paid time is applied (`DW::Shop::Item::Account->_apply`) and the purchaser gets emailed at the point where the cart is fully processed (`DW::Shop::Cart->_notify_buyer_paid`).  In bin/worker/paidstatus, the first action happens at line 359 and the second action happens at line 380.

I'm assuming this bug was filed on the basis of support requests from buyers who never received the email, but it's not like we've never failed to deliver emails...

**Comment by rahaeli** [comment]
Hmm. Yeah, and I don't remember ever getting an emailed receipt when I buy paid time for someone, either. Hmmmmm.

Lemme make a test payment ...

**Comment by rahaeli** [comment]
Huh. Okay, this is just my lousy memory + people complaining about emails not being delivered, I guess! The receipt you get when you pay for someone's account does include a link to the receipt. For some reason I was sure it didn't.
