### ISSUE TITLE
Whitelist Soundcloud embeds

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1989]
Sample code:

`<iframe allowtransparency="true" scrolling="no" frameborder="no" src="https://w.soundcloud.com/icon/?url=http%3A%2F%2Fsoundcloud.com%2Fundefined&color=orange_white&size=32" style="width: 32px; height: 32px;"></iframe>`

Request: https://yhlee.dreamwidth.org/2263706.html

**Comment by ninetyd** [comment]
Soundcloud has already been whitelisted (https://github.com/dreamwidth/dw-free/blob/develop/cgi-bin/DW/Hooks/EmbedWhitelist.pm) but, if I remember well, embeds don't work correctly because... and that's where I'm drawing a blank. :) Maybe they've changed their code in the meantime, though.

**Comment by srukle** [comment]
I can't see what's important in the iframe example. Perhaps it's Soundcloud? I may have to look into this later.

**Comment by kareila** [comment]
Yeah, the URL above looks like an icon link, not an audio link.

If I go to Soundcloud today and grab a random embed code, it looks like this:
```
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/306953430&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
```
Our whitelist pattern matches that, and if I try pasting it into an entry, it works for me.  I can only conclude that any problems are being caused by one of two things: either copying and pasting the wrong code from Soundcloud's confusing UI, or having a Flash blocker enabled (the Soundcloud player appears to use Flash).
