### ISSUE TITLE
Logged-out /login and logged in or out /openid/ give 'not fully secure' warning

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2072]
https://www.dreamwidth.org/support/see_request?id=36151 for the log in page.

I guess these are high-traffic pages so a fully secure status would be nicer.

**Comment by alierak** [comment]
The HTTPS versions of these pages appear to work fine. However, we are still in the opt-in beta phase of HTTPS everywhere (which would only apply to logged-in users). No pages currently force everyone to HTTPS, but anyone can visit the HTTPS version of a page if desired.

**Comment by ninetyd** [comment]
Ok https://www.dreamwidth.org/login is secured but https://www.dreamwidth.org/login?ret=1 and https://www.dreamwidth.org/openid/ aren't (Chrome).

**Comment by alierak** [comment]
Ah, thanks, that helps. They showed up fine in Firefox. Testing in Chrome, I can see that the logged-in version of the login page is fine, but the logged-out version contains a form whose action URL is http://www.dreamwidth.org/create and that will need updating to use a // url. For /openid/ I think the problem is in a CSS background image for the "input.sexy" style.

**Comment by kareila** [comment]
If approved, #2088 will fix the problem with the openid page.
