### ISSUE TITLE
Wrong log in link when journal is NSFW

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2180]
If you go to a NSFW journal while logged out (e.g. https://fandomcalendar.dreamwidth.org/), the login button in the top right corner has an incorrect link: https://username.dreamwidth.org/login instead of  https://www.dreamwidth.org/login.

**Comment by kareila** [comment]
I believe this is caused by TT code that uses `href="/login"` instead of `href="[% site.root %]/login"`.

Two places where I see this happening:

- schemes/common.tt line 138: this is the exact line I see printed in the source for the reported instance. Part of `block.accountlinks`.

- schemes/global.tt line 21: this is a very similar line that needs the same fix. Part of `block.menunav`. I've determined that it displays on narrow screens in lieu of the normal login button and navigation menu.

**Comment by ninetyd** [comment]
Just noted than on my phone a log-in window pops up instead. I don't get it on my laptop.
