### ISSUE TITLE
Notification emails should contain https links

### ISSUE THREAD

**Issue by pseudomonas** [dreamwidth/dw-free#2218]
At present notification emails contain plain http links to DW. These should presumably be https?

**Comment by kaberett** [comment]
#1354: this has been implemented, but is tied to a site-wide "are we using HTTPS everywhere?" switch, which has not yet been turned on for DW. (My understanding is that it will be when Dreamwidth's HTTPS Everywhere comes out of beta.)

**Comment by kareila** [comment]
It's starting to cause enough confusion with recent browser/extension updates that I would be good with checking whether the site accepts SSL, instead of whether we want to force SSL - after all, once we force SSL, the user will be redirected no matter which is requested. I think that config parameter is USE_SSL?

**Comment by pauamma** [comment]
Is this still relevant? I now have https  in all my email comment notification links, and https://www.dreamwidth.org/beta tells me I don't have the HTTPS Everywhere DW feature enabled.

**Comment by kareila** [comment]
The sitewide config switch that @kaberett alluded to above was flipped on at the end of September. So yes, we can close this.
