### ISSUE TITLE
Incorrect tab order on old Create Entries page

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2247]
https://www.dreamwidth.org/support/see_request?id=37982

> When selecting the "Edit Date" option on the old Post an Entry page (foo.dreamwidth.org/update) to choose a specific date and time for the entry to be posted with, using the Tab key to move through the fields of date and time allows me to select the month, day, and year, in order. The next press of the Tab key skips to the "View Thumbnails" link associated with icons instead of proceeding to the hour and minute fields, as I would expect it to do.

**Comment by pauamma** [comment]
I think the cause is that month, day, and year don't have tabindex values. Quoting from https://www.w3.org/TR/html4/interact/forms.html#h-17.11.1 : 

> Elements that may receive focus should be navigated by user agents according to the following rules:
> 
> 1. Those elements that support the tabindex attribute and assign a positive value to it are navigated first. Navigation proceeds from the element with the lowest tabindex value to the element with the highest value. Values need not be sequential nor must they begin with any particular value. Elements that have identical tabindex values should be navigated in the order they appear in the character stream.
> 2. Those elements that do not support the tabindex attribute or support it and assign it a value of "0" are navigated next. These elements are navigated in the order they appear in the character stream.
> 3. Elements that are disabled do not participate in the tabbing order.

So it's entirely possible that when you select with the mouse (or through a JS action) an element with no tabindex (which I think is like having it set to 0), elements with a tabindex > 0 are "past" in the tabbing order and never reached. Now to test that theory...
