### ISSUE TITLE
update LJ::User methods in DW::Media to be methods on the DW::Media class instead

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2258]
Currently, it lives in cgi-bin/DW/Media.pm. But since it's a LJ::User method, it should live into the appropriate LJ::User::* submodule, probably LJ::User::Data.

**Comment by zorkian** [comment]
Not 100% sure I agree.

Originally, the idea was 'put all LJ::User methods in submodules' and that's well and good for some things, but at some point I got really frustrated at trying to remember where in the 'verse different methods were scattered so I started organizing them by functional area.

I think either is valid and both have pros and cons. Probably we should make a decision about where the code should live, and I'm slightly in favor of organizing things to reduce logical jumping distance when you're looking at code. What I mean by that is: if you're messing with `can_upload_media` it's probably going to be talking about quotas and things, and that code is probably mostly in/around the `DW::Media` code, so keeping them proximal reduces how much travel you have to do within the codebase.

It also aids learning the code since if you want to learn about the Media system you can read that directory and it's pretty well self-contained. Rather than having to just grep for media and hitting up every file that has a reference and trying to piece it together.

On the other hand, it makes it pretty hard to know all the possible things an `LJ::User` object can do, so it's definitely a tradeoff.

Any thoughts?

**Comment by pauamma** [comment]
IMO,

> On the other hand, it makes it pretty hard to know all the possible things an LJ::User object can do,

trumps the other considerations on least-surprise and code learnability grounds. (Trying to put myself in the shoes of someone exploring the codebase for the first time.)

**Comment by zorkian** [comment]
I agree that it makes it hard to learn 'what an LJ::User can do' but that is only one specific question.

Having hugely intertwined systems with few API barriers is much harder to grok than well separated systems with clear APIs that exist in a very small set of files. I think it's hard to argue that spreading methods about the media system around the codebase is 'easier' to understand than centralizing them.

**Comment by Sophira** [comment]
I'm personally a fan of keeping things all in one file, for the reasons Pau mentioned. (And even though I'm fairly sure there's no case where LJ::User and DW::Media will ever not be loaded at the same time, it still feels strange to have a  subroutine's existence depend on whether an unrelated module is loaded. That's probably a minor thing though and could theoretically be considered a positive though.)

How about a compromise? Move the sub to DW::Media as a static sub, then have a stub in LJ::User which calls the subroutine in DW::Media?

**Comment by zorkian** [comment]
As a different compromise, how about there isn't any linkage from
LJ::User? Is there much of a good reason to have the user object contain
a billion methods anyway?
$u->media_upload_quota vs DW::Media->quota($u)?

**Comment by pauamma** [comment]
zorkian's solution looks acceptable to me.

**Comment by Sophira** [comment]
If we did this, we probably wouldn't want to use `->` as that will pass the classname to the subroutine for no benefit. The following two libes of code are exactly equivalent:

    DW::Media->quota($u);
    DW::Media::quota("DW::Media'', $u);    
 
Generally, unless there's a need to know the clsssname in the sub specifically (for example, when `bless`ing a scalar), I would personally just use it as a regular static sub:

    DW::Media::quota($u);

@zorkian - how do you feel about this?

**Comment by Sophira** [comment]
Dang, I meant `"` and not `''` in the code block in my last response - sorry. I can't easily edit it on mobile!

**Comment by zorkian** [comment]
Yes, please pass the class name and that is the style I've been using
for a while now. See Media and BlobStore etc.
