### ISSUE TITLE
Account keeps switching to main journal in the Select Community Style page

### ISSUE THREAD

**Issue by ljwrites** [dreamwidth/dw-free#2384]
Working with Firefox 64 on Mac OS X Yosemite, I get an error from the "Select Community Style" page where, every second or third change I make to the community style, I am switched over to my main journal without warning. As a result I changed my journal's theme where I meant to change the community's, edited my journal's subtitle by mistake etc.

**Comment by rahaeli** [comment]
Hi there! This isn't the place for reporting problems with your DW account -- it's for coordinating improvements to the underlying code that runs the site. The place you want is https://www.dreamwidth.org/support instead! 

Having said that: this is one of three problems, all fixable on your end: 80% of the time something like this is browser caching, 9% is extension incompatability or bugs, and 1% is your ISP incorrectly caching the response from our CDN/DDOS-protection provider.

If it's browser caching: clear your cache and set your browser to always pull new versions of the page.

If it's extensions: start by disabling all login-related and cookie-related extensions (such as LJ Login, LJSwap, etc), then log out and log back in again (important in order to clear your login cookie and re-set it). Those login-related extensions, especially if they were designed for LJ and not DW, are notorious for causing these sorts of problems.  If that doesn't work or you don't have any of those extensions installed, you'll need to do a bit of funnel testing to narrow down the problem. (Start by disabling all extensions and see if it's fixed. If it is, add back half your extensions and see if it comes back; if it does, the problem is with that half of the extensions, if it doesn't it's with the other half. Once you've identified which half, enable all those extensions + half of the other, and see if it comes back. Etc, until you're adding extensions one by one to identify the culprit.)

If it's ISP caching: also set your browser to always pull new versions of the page.

If none of those things work, then open a support request! I'd put $29 and an alligator purse on the underlying problem being extensions, and support is going to as well, so if this winds up being the .001% of cases where none of the above fixes it and you do need to open a support request, be sure to include that you've changed your cache settings and ruled out extensions problems.
