### ISSUE TITLE
Tagnav highlighting not always working

### ISSUE THREAD

**Issue by woggy** [dreamwidth/dw-free#2396]
I'm stepping through a tag's history and sometimes the new page doesn't have the tag highlighted (and thus, the arrows are grayed out and I have to reselect.)

This only seems to be occurring on tags that are at least three (space-delineated) words; tags with two words are behaving normally.

The url argument includes the entire tag name as expected.

**Comment by kareila** [comment]
Can you give us an example of a tag that exhibits the behavior for you, so we can test it on various platforms and browsers?  Also what platform and browser are you seeing the problem in?

Also, when you say "sometimes", about how often is the problem occurring with a particular tag?  Is the behavior consistent or not?

**Comment by woggy** [comment]
https://kaberett.dreamwidth.org/tag/a+few+of+my+favourite+things as an arbitrary example; the first place I noticed was access-locked.

Mobile (Android) Firefox 64.0.2, happens Every Time on tags where it's a problem. Sometimes was meant to indicate that not all tags have the issue.

**Comment by kareila** [comment]
Thanks for the clarification!

**Comment by alierak** [comment]
In htdocs/js/journals/jquery.tag-nav.js, near the bottom, text.replace(' ', '+') will only replace the first occurrence of a space in the tag. I think it needs to replace(/ /g, '+') in order to replace all. Not immediately clear whether there might be other special characters for which this code would fail to find and click the selected tag due to similar URL encoding/decoding issues.

**Comment by woggy** [comment]
Spot-checking a couple of special characters (both of which are being escaped in the url): ! seems to work As Expected. # doesn't.

**Comment by alierak** [comment]
Ok - if I'm understanding this right, we have on one side the encoded tag from the part of the current page's URL after the #tagnav-, and that gets URL-decoded (but the JS decodeURI function won't decode + and won't decode all possible %xy characters). On the other side we have the text of a tag name as displayed in a tag link. Maybe this thing needs to operate on the URL of the tag link rather than the text of it.

**Comment by alierak** [comment]
Oh, I see, it should be using decodeURIComponent instead of decodeURI. That ought to handle all the %xy characters, and then we'd just need to worry about the space / + replacement.

**Comment by alierak** [comment]
Claiming.
