### ISSUE TITLE
Redesign the talkform

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2480]
Issue #2437 is all over but the screaming, and that means it's time to decide what to do about the talkform. I think I need signoff from @zorkian and @rahaeli before moving on any of this, but I also _want_ feedback from basically everyone.

I have four questions, some of them larger than others.

- ~Can I kill spellcheck?~ Yes, #2481 
- ~Can I kill or drastically mutate subjecticons?~ Almost definitely, #2483 with a hard dependency on #2482 
- How should the identity controls work? (TBD)
- ~Editing affordances?~ Yes — support Markdown, let users disable Markdown (and remember their choice), and make editor buttons emit MD or HTML tags depending on mode. #2573

## 1. Can I kill spellcheck?

Both the talkform and the less-quick reply have a spellcheck checkbox. **Does Dreamwidth need this in 2019?** Even the worst desktop browsers have had spellcheck in textareas for the last ten years at least, and mobile platforms all have spellcheck in their keyboards. What does preview-spellcheck actually add?

## 2. Can I kill or drastically mutate subjecticons?

**Nota bene: I am not talking about userpics here. Userpics obviously stay.**

When it forked from LJ, DW inherited this weird set of about eighteen incredibly shitty icons that look like this: ![the skull subjecticon](http://www.dreamwidth.org/img/talk/md02_skull.gif) Super awesome PHP-BBS-circa-y2k stylings on these. They are called "subjecticons," not to be confused with Decepticons.

- You can choose one per comment (_not_ top-level post), and it'll appear above or beside the subject header (presentation is delegated to journal CSS).
- They're hardcoded. There's no abstraction for working with a DW site's collection of subjections.
- They're ONLY available from the full-size talkform; impossible to use them in the quickreplies.
- They have a dedicated button in the full talkform.
- Every one of them (with the sole exception of ![hitchhiker boi](https://www.dreamwidth.org/img/talk/md01_alien.gif)) has a one-to-one replacement in the standard set of emoji circa 2015. 🙂😉😊😮🙁😠✅⭐️✉️👀☠️🤢☢️😎💡👎👍
- Raise your hand if you actually use these on the regular.
- Raise your hand if you _knew these existed._

**Zeroth question: Please raise all affected peoples' hands for them.**

Subjecticons are stored in the database as a distinct property of each comment, I think as an ID like `sm09`. Would someone with access to the prod databases be willing to do some queries and calculate what percentage of the last three years worth of comments include a subjecticon?

**First question: Can these please just _go?_**

I know deleting features is socially hazardous, but please answer from the dark silence of your soul instead of the reflex flipout of your user support persona. (The reflex flipout of my own user support persona commiserates with you, but still.)

I think no one's been motivated to actually make a decision about this feature because it's been relegated to the Old Talkform all decade, and everyone knows the Old Talkform is shitty and not to be used by normal people. But now that the talkform is maintainable, it's time to end that way of thinking and bring the comment forms together! _If subjecticons should stay in the talkform, they should also go into both quickreplies._ Do you want that? If not, I think it's unreasonable to want them to stay in the talkform.

**Second question: _If not,_ can we just replace them with Big First Subject Emoji?**

(I submitted this as a `dw_suggestions` post several weeks back, but `dw_suggestions` might be sleeping.)

When I raised the possibility of killing subjecticons before, someone said they were too beloved by _someone,_ possibly a subset of RPers. If that's really & truly the case, would those people be satisfied with an alternate interface for showing a little picture above the comment subject? Specifically:

If the first character of the subject is an emoji, AND the second character is NOT an emoji (to preserve the integrity of important sequences like 😝😜😛🤪😛😋😛😝😜😋😝):

- The first character will be removed from the subject and displayed outside the subject in a special element.
- By convention, this special element will be styled by S2 layouts as a big-ass emoji, font-size 32px or thereabouts.
- That big-ass emoji will be displayed using:
    - Preferably, the system's default emoji font.
    - If that's untenable for some external reason I'm not aware of, a standard freely available emoji set like Twemoji.
- The removal and big-ass re-display of the first emoji will be solely part of the display logic:
    - In the event that a user edits their comment, the emoji will still be present in the edit form's subject field as the first character.
    - In the event that some user replies to that comment, the default reply subject will be `Re: <big-ass emoji> <remainder of subject>`.
    - In the database, the subject will be persisted as originally written.

When answering this question, please combine various constraints — for example, while there might be theoretical technical situations where "emoji don't work," _do those situations apply in real life to a meaningful subset of the specific users who currently use subjecticons heavily enough that we can't just remove them?_

## 3. How should the identity controls work?

Extracting the talkform taught me many things. `</glados-voice>` Foremost among them was that it used to be _really hard_ to express what you wanted the "from" controls to do.

Now it's less so, so: what should they do and how should they look?

I have two semi-concrete proposals:

### Drop-down with optional appendix

![IMG_9477](https://user-images.githubusercontent.com/484309/58935429-49e6a180-8722-11e9-8494-de5a28c46b0c.JPG)

Compress the "from" controls into a single drop-down that starts with the default option for the current conditions selected. If the currently selected option needs extra info (logged-out DW user, logged-out OpenID user), show the sub-form below; if not, not.

### Radio buttons with "other" and "current" compressed

![IMG_2725](https://user-images.githubusercontent.com/484309/58935438-523edc80-8722-11e9-89f0-e86062ed5bbd.JPG)

Much like today, use radio buttons to expose the full range of "from" options. Unlike today, rearrange which things get conflated:

- The third field, "currently logged-in user," accommodates either a site or openID user. You can only be logged in as one at a time, so this just makes more sense.
    - The third field is absent if no one's logged in. Two fields only.
- The second field, "other account" — its label transforms into a drop-down once selected, and exposes the relevant child form fields below. It defaults to "site user" with username/password/login fields, but you can switch it to "openid" and get the URL/login fields instead.

Both of these options leave room for future expansion of login options, not that I know of anything specific that's actually planned. Facebook and Twitter are sure looking like dead-ends these days. Maybe we'll want "log in with Apple," lol.

**No-JS fallback:** (because it's good for your soul, even if it's not generally realistic) The dropdown acts like normal, but _all_ (both) appendix forms display below it. Either we use backend form validation to reject submissions that have wrong fields filled out, or (better, IMO) we just ignore fields that aren't relevant. Can include no-JS instructions that get display: none'd otherwise to help resolve the confusion.

## 4. Editing affordances?

I know someone's working on a Markdown-based editor interface for the beta new-post page, but I don't know how close it is to being usable, and I don't know whether they've considered the commenting forms. **What's the status on the "RTE," and can I add some stupid markup buttons to comments in the meantime?**

Ideally I want comments to get Markdown powers too, and I want that to be controlled with a UI checkbox instead of a !Secret !Word. And then I want the comment forms to get UI buttons for basic Markdown constructs like `<strong>` / `<em>` / `<ul>` / `<ol>` / `<a>` / `<img>`, which should all be shared with the new-post page.

But if that's more than two months or so in the future: lack of Markdown makes comments bad, and I'd like to ameliorate that with some buttons and keyboard shortcuts for the most basic markup options. In particular:

- "b" button/cmd-B: `<strong>`
- "i" button/cmd-I: `<em>`
- "quote" button: `<q>/<blockquote>` with selection
- "link" button: `<a href="URL">TEXT</a>`
- "@" button: `<user name="SELECTION">`
- "`<>`" button: `<raw-code>`

Most of these should transfer pretty well to a post-Markdown regime, yeah? Is there any reason not to add them in today's HTML world?

These buttons should appear in the talkform AND both quickreplies.

**Comment by zorkian** [comment]
1) Spellcheck. Yeah, kill. For the reasons you cited but also that our spellcheck certainly doesn't support other languages while the in-browser/phone versions do. We provide a strictly worse experience with no real value for our users. (Also the machinery inside to do it is kind of gnarly!)

2) I'm getting the stats you asked for (it will take some time, the data is not indexed in a helpful way. One cluster of ~208m comments has ~500k subjecticons which implies a usage rate of around 0.2%. Based on this data, this feature should be removed and people can use emojis if they feel like it!

3) TBD, haven't thought hard enough yet.

4) I think anything RTE/markdown editor based for the forms are at least two months out, I haven't seen any actual progress in a long time. People are interested but it hasn't resulted in output yet. Is there any reason not to just enable Markdown by default (with a user option to disable it) and make the buttons spit out Markdown (or HTML if you as a user have it disabled)?

**Comment by pauamma** [comment]
I think these questions should be discussed in a more user-oriented forum than here, perhaps dw_news.

**Comment by SporkyRat** [comment]
> I think these questions should be discussed in a more user-oriented forum than here, perhaps dw_news.

Some of them, yeah.  Some of them also need to be discussed here before they go to users though, like spell-check.  We had a support request at one point telling us that our spell-check was...uh, I think it was 'ablelist'?  Something like that.

**Comment by kaberett** [comment]
I think it was kink-shaming.

**Comment by SporkyRat** [comment]
Yeah, probably.  It was being a not very good spell checker, anyway.  

> I think it was kink-shaming.

**Comment by rahaeli** [comment]
1) We have floated removing spellcheck before and each time someone complains, but fuck it, it's almost impossible to maintain a custom dictionary, it's not very good at recognizing contractions, let's just kill it.

2) The subject icons are heavily used in a very small subset of use cases (anon discussion comms) and they're really attached to them. (Not that this is a barrier to doing anything, just explaining why the usage stats will show very low usage but suggestions to get rid of them always prompt very loud yelling.) I see no reason why they can't be replaced by emoji, though. Instead of specialcasing and parsing subjects, how about an emoji picker inline? (Quick search says that there are a few implemented in JQuery.) I'm not enthusiastic about another "hidden feature that works if you know the right magic" design -- we have a lot of them already, and in practice they just stay hidden and unused. Will the redesign in 3 get us any useful space to put an emoji picker without it being too complicated?

3) I am very much for redesigning that workflow, and the quick sketches all look reasonable. Use cases to keep in mind there to make sure they're not any more difficult than they currently are: comment as anonymous even when logged into an account (anon discussion comms), comment as another of your accounts while logged into a different account (RP -- although in practice a lot of RPers use cookie swap extensions to quickly switch).

3a) Related: a project we've been wanting to do for a while is linked accounts: linking your accounts would let you easily switch logged-in accounts (ala the "work as" dropdown) without having to use cookie swap extensions. We've been blocked on that for a while because it really will take someone six months or so and a few rounds of workshopping to solve the eight billion social, technical, and UI questions that it raises (and because the most logical and easiest answers to a lot of the technical and UI questions generate perverse incentives for two separate people to link their accounts), but I mention this in case it changes any of your decisions here.

3b) Yes, a no-JS version is a must, since commenting is a core feature of the site! It's fine if you want to redirect to a separate page (the way quickreply redirects to what used to be talkform.bml (and might still be) if you want to change login settings) instead of having everything just hanging out there naked; whatever's easiest.

4) The stumbling block on all-comments-Markdown-formatted is that RPers *frequently* use asterisks for indicating actions in the middle of comments in ways that shouldn't be italicized, as does my corner of fandom. It's also common for a lot of people with disabilities to prefer marked-with-asterisks to italic for emphasis, because visually spotting the asterisks is a lot easier at a glance than italic and italic can be hard to read in some fonts and at some very large type sizes. So, at the very least, people need to be able to turn it off.

That having been said, bold/italic/quote/link buttons would be helpful for comments and I like the idea of adding them!

**Comment by nfagerlund** [comment]
@rahaeli:

1) #2481 

3b) 👍🏼 say no more. 👍🏼 

3a) Future linked accounts pushes me towards the dropdown select, rather than the radio buttons. That way, someone with linked accounts just gets N extra options in the dropdown for switching to their alts, whereas extra radio buttons could eventually push the form down the page to an annoying extent. 

4) 👍🏼 An option to disable Markdown is a must; I'd never consider omitting it. (But even with markdown enabled, you can use `\*` for a literal asterisk, and I think many RPers will find they don't mind paying an occasional backslash tithe to get the other Markdown niceties.)

There was some convo about this in the channel, and it interacts with the "disable autoformat" option. My current thinking is that we have three separate text modes, which should be displayed as a drop-down in the comment form's "formatting" row:

- Markdown
- HTML plus line breaks
- Raw HTML

yeah?

2)  I have a few follow-on questions about this area:

- The only problem with a UI emoji picker is extra javascript and media weight on the page. I suppose we could just omit that from style=light and not worry about it too much?
- It sounds like you're in favor of having a specific replacement for subjecticons rather than just saying "use emoji in the normal subject," right? 
- If we go with "subjectemoji" as a replacement, should it stay as a distinct property of the comment? (Probably just re-using the subjecticon field?) 
- Should we rely on whatever the system emoji font is, or use images like https://twemoji.twitter.com/? 
- Do we need to think about using something like twemoji for all emoji in "normal" content in journals? (I'm against this fwiw; system emoji fonts exist and look "normal" to readers, JS+img character replacers add load weight and runtime slowness, and the wait for your OS to support the season's new emoji is kind of a cultural ritual by now.)

**Comment by azurelunatic** [comment]
Re: 4, the last time I tried to escape an asterisk I tried like 3 things, got it wrong despite a reference, and gave up. I'm not an un-technical person, but my initial experience soured me on the entire concept.

**Comment by nfagerlund** [comment]
K, that's legit. With "disable markdown, and the formatting buttons output HTML tags instead" I think we have that use case handled.

**Comment by rahaeli** [comment]
> The only problem with a UI emoji picker is extra javascript and media weight on the page. I suppose we could just omit that from style=light and not worry about it too much?

Hmm, ?style=light is just a separate skin on top of the same HTML all the skins use, so it might be harder to do that. I'll look a bit and see if there's a lightweight enough widget that I wouldn't feel bad about adding it for everything.

> It sounds like you're in favor of having a specific replacement for subjecticons rather than just saying "use emoji in the normal subject," right? [...] going whole-hog on this seems really heavyweight.

Ughhhhh I keep changing my mind. Let me think out loud:

* Invisible features that are only discoverable if you read the FAQ or whatever are terrible. (Did you know that you can add symbols to the end of your username when logging in through the login form in the site skin/navstrip to keep yourself logged in and/or bind your login cookie to your IP address? No? That's okay, nobody else does, because it's an invisible feature that's only discoverable if you read the FAQ!) (Well, we might have removed that by now, I can't remember 100%, but you get the gist.) So adding something to parse out an emoji as first character in the subject line makes me hesitate on that principle. It might still be the best solution, but it's really hard to get past my instinctive aversion.

* Anon memes use the subjecticon as a half-assed replacement for user icons (to clarify, the half-assedry is on our point, not theirs), which are major social metadata and a key differentiator between us and other sites -- the fact that anon comments can't have user icons removes that social metadata that people are so used to using. So my hesitation to removing them comes from not wanting to completely eliminate that social metadata, even if this exact implementation is half-assed. Well, not even half-assed. Quarter-assed.

* Anon memes are a small percentage of communities, but tend to have a lot of participants, and those participants tend to be some of the more invested users. (One of the big ones has to open a new post for discussion every 36-48 hours, for instance.) So, small number of communities overall, but changes may have a disparate impact. Also, their participants are vocal about displeasure. Remind me to tell you about the time we fixed a bug in how anon comments display and I lost the next 48 hours of my life...

* You're right that doubling down on changing subjecticons to emoji via an emoji picker is awfully heavyweight, and really committing to what's essentially a parallel system to user icons to communicate that kind of social metadata is dumb when it's really only useful in the anon case (because logged-in users universally use user icons to contextualize their comment if they want to add the social metadata). 

* But ARRRRGH.

This may need to go to the userbase for a temperature check and see what kind of reactions we get. I'm *mildly* leaning towards removing them entirely, but it's only a mild lean. We usually get pretty good arguments one way or the other out of our temperature checks, even if people don't always realize that they're making the argument they're making.

**Comment by rahaeli** [comment]
Orrrrr Alyndra could have a great idea for how to split the difference, leading to #2482 :)
