### ISSUE TITLE
QR: change order of post buttons

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2528]
New qr has the main “post comment” button first, on the left. 

That came from the “quicker reply,” as with many things. The old less-quick reply had it on the right instead. 

Which place is correct? Left is nicer on mobile, but actually it’s “first” that’s nicer on mobile and flexbox lets you lay buttons out backwards if necessary, so it could be right and still first. That might be unintuitive to left-to-right language readers tho. 

Could also move everything right and bump the auxiliary buttons down a row. 

Personally I’m liking left well enough.

**Comment by rahaeli** [comment]
I think being inconsistent between mobile and desktop is worse than just changing it now and making everybody retrain themselves!

My vote goes to "post comment button on the right where it's always been" because of 20 years of muscle memory, but I'm willing to be convinced otherwise. I think "on the right" is more standard, though? Like, this box I'm typing in now has the "comment" button on the right.

**Comment by nfagerlund** [comment]
Mmm, good call — twitter uses on-the-right, facebook uses on-the-right, mac os dialogs have the "OK" button on the right, that seems to be what's generally expected. 

The only wrinkle is how wide the form can get. Right now it's capped at 45rem (was previously smaller, but some desktop users found that constricting), but that's still some distance: 

![image](https://user-images.githubusercontent.com/484309/60131516-69d01a80-974e-11e9-87ec-1b55873082b0.png)

Now, actually that's about the same size as this github form! But that's a bigger button target than we have, because they're using a custom control, and we can't/shouldn't do that, probably.

Anyway, I'm willing to try that. Should move the more options button up and re-add the user indicator, at the same time -- that way we'll only have the post, preview, and quote buttons down there.

**Comment by rahaeli** [comment]
Yeah, since more people tend to be right-handed and English reads left-to-right, generally the important, frequently-used action goes on the right. (Apple's human interface guidelines circa System 6-7 used to mandate that, but they've gotten muddier than the Golden Era lately and never addressed web pages, just system widgets.) But It's Harder(tm) With Mobile, etc.

**Comment by nfagerlund** [comment]
claiming
