### ISSUE TITLE
Nail down formatting dialects and `editor` prop

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2608]
DW uses several different dialects of formatting. Currently they're implemented as an array of semi-independent feature switches and heuristics. But @zorkian centralized and normalized some stuff in the HTML cleaner, and now we have a nice handle for rationalizing some of this stuff and guarding archived content against future formatting shifts. 

I propose we centralize all content formatting questions in the `editor` prop on entries and comments. (That prop previously existed for comments, and is currently used to mark emailed replies as markdown.) For existing content with an undefined `editor`, we can autodetect into the appropriate older dialect before handing off to the cleaner function; for all new content, we’ll save an explicit editor value. 

Note that this is about the formatting languages used in the *content,* not about the different kinds of output formatting (e.g. normal display, crossposting, truncate, etc.). 

Here are the dialects I'm aware of, and their behavior.

- `html0` — text w/ HTML tags for formatting, written between 2009 and mid-2019 OR imported from LJ at any time.
    - Auto newlines (replace `\n` with `<br>`)
    - Auto links (wrap bare text URLs with a clickable link to that URL)
    - Allows special DW tags (cut, user, etc.) plus legacy LJ tags (lj-cut, lj, etc.)
    - No `@mentions`.
- `html1` — text w/ HTML tags for formatting, written from 2019 onward.
    - Auto newlines
    - Auto links (wrap bare text URLs with a clickable link to that URL)
    - Allows special DW tags (cut, user, etc.) plus legacy LJ tags (lj-cut, lj, etc.)
    - Yes `@mentions`.
        - excluded contexts: code, pre, textarea, raw-code, twitter's magic blockquotes.
    - When to bump: Adding new syntax on the order of `@mentions`, adding new kinds of auto-formatting that would misinterpret older content, removing legacy lj tags, changing how auto line breaks/paragraphs work.
- `html_raw0` — real HTML, possibly generated by something but still intended for posting on DW. Also imported from LJ with the preformatted flag set.
    - No auto newlines, gotta use p tags. No auto links either.
    - Allows special DW tags (and LJ forms).
    - No `@mentions`.
    - When to bump: Might not ever need to, but if we decided to restrict allowed tags or something, then maybe. Also if we wanted to enable `@mentions` here. 
- `html_extra_raw` — Real HTML, not originally intended for posting on DW. (Syndicated content, for the most part.)
    - No auto newlines or auto links.
    - No special DW/LJ tags.
    - No `@mentions`.
    - When to bump: Probably never, because the definition of “what is html” mostly isn’t our problem and html5 is a living standard.
- `markdown0` — Markdown implemented with `Text::Markdown` module.
    - Yes `@mentions`.
        - excluded contexts: code, pre, textarea, raw-code, twitter's magic blockquotes.
    - Gets processed by Markdown, then treated as basically `html_raw` except for allowing `@mentions`. (So yes DW/LJ tags, no auto-links, and paragraph breaks were already handled by the MD step.)
    - When to bump:
        - If we ever change markdown processors or fork our existing one (to get better performance, new syntax, etc.). (If anyone is thinking "c'mon, how incompatible could two markdown processors be," please just trust me on this one. I can go into details later.)
        - If we decide to add new syntax to our own Markdown dialect, something on the order of `@mentions`.
- `rich0` (?) — Generated by the old RTE.
    - Actually, I‘m pretty positive this is just `html_raw0`. So, probably doesn't need a separate format.
    - Looks like RTE correctly sets the preformatted flag, so autodetection of old content should catch that it's `html_raw0`.
- `rich1` — Need to discuss w/ @wohali!
    - My tentative understanding is that it should _act_ like `html_raw0`, but needs a separate editor ID so that we can warn people whenever they're switching to or from RTE that there might be some lossy formatting conversion.
    - Do we need to handle special tags differently? Unsure yet, depends on editor’s behavior.
    - `@mentions` hopefully just handled interactively by the editor and saved as normal user tags.

**Comment by nfagerlund** [comment]
Related to #1999 and #2573

**Comment by wohali** [comment]
OK, here's what I'm thinking for a mapping from dialects to editor>

`html0`: extra frustrating to deal with. I am thinking we dump these posts into a raw textarea and offer no assistance.

`html1`: Again, auto-newlines make these super annoying to deal with. Raw textarea again seems best.

`html_raw0`:  This is effectively what I think the new RTE targets. We can optionally have the RTE auto-convert `@mentions`, but if you want to add support here for then natively I can look at that as well. I'd like to find a few posts in this format and load them into the RTE to see if they render correctly. If not, we may want a small bump.

`html_extra_raw`: these shouldn't ever end up being edited, but if they do, raw textarea again.

`markdown0`: We have the potential to use the RTE in Markdown mode, which would be entirely distinct from the normal RTE version - neither would ever load the other's output. It'd look like a super scaled down RTE that supports _only_ the things Markdown supports, and outputs Markdown. Because it's really just an assistive toolbar, it wouldn't be doing any conversion, so this is a snap to implement. It's a lot like that old ticket that was abandoned a long time ago.

`rich0`: I agree that I think this is just `html_raw0`.  We can punt on importing this into the new RTE...or we can offer people a one-time "Load into the RTE? This may introduce some minor formatting errors. You can cancel if you don't like it" and then force a conversion on save to `html1`.

`rich1`: Shouldn't be needed.

Also: I'm hoping this value above (still?) gets passed to the editor render page at least; it probably also need to be passed down thru a variable to JS. I'm not sure we need a separate editor mapping field, unless you really want to do one. It's like 3 lines of code, isn't it? But if you want to for clarity, I'm not opposed.

@nfagerlund said to me on Discord:
> as for switching back and forth between rte-compatible and Non, I think I’d be in favor of throwing a warning dialog that says “this might lose your formatting” if you switch to OR from rte, and then making a best effort. But the main use case I’m thinking of is “started typing in the wrong editor, goddammit”

my response:

the goal of the new RTE is that it always puts out perfect HTML, every time, no need for translation. The only difference between it and existing html_raw is that it'll be pretty printed. If people don't mind that change, they can load anything in too. We'll have to see.

As for switching back and forth, that's what's held everything up for so long. I'm _considering_ saying: if you're in html0, html, or html_extra_raw then you can't use the RTE, ever, sorry. The others we can handle with the popup, let them load the editor (which munges once, on load), and if they don't like the changes, they can cancel the edit and go back to a plain textarea box. I'll need to play with the UI bits on this a bit to make it easy on the eyes, shouldn't be too hard.

If you're in the RTE it'll have its own "HTML" mode for raw editing, that still will get pretty printed, so I don't think the backend ever needs to know about it, nor do we need a popup...but I know how to intercept the mode change if we want to flash one up. But in this proposal, you absolutely wouldn't be able to toggle between the RTE and an editor that handles `html0` or `html1` anymore **with automatic translation,** that's the "nearly impossible to get right" thing. We can simply dump you over with no translation and see how it goes, I guess. And yes, that could have a pop-up.

What do you think?
