### ISSUE TITLE
"entered account name but posted anonymously" error with saved passwords in browser

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2629]
Reported with Chrome: https://dw-maintenance.dreamwidth.org/81236.html?thread=3193428#cmt3193428

I hate this. :| 

- The JS in the talkform includes a thing that wipes out the username/password values as soon as you switch to another poster option. That's supposed to prevent this.
- But it looks like maybe Chrome is re-populating the saved username/password values ON FORM SUBMIT, when the JS can't do anything about it. 
- The backend handler for that form has deliberate behavior to give this error instead of just saying "oh, it's anonymous, I'll ignore the user/pass." Does... does anyone know why?? My best guess is that it's to field the no-javascript case, since all of the fields are visible at once so it's more possible for a user to get confused and send conflicting inputs. 

I have a theory, which is that we could DISABLE user/pass inputs on switch in addition to blanking them. That should mean that the browser won't send those inputs to the backend at all.

**Comment by rahaeli** [comment]
> Does... does anyone know why?? My best guess is that it's to field the no-javascript case, since all of the fields are visible at once so it's more possible for a user to get confused and send conflicting inputs.

Got it in one. It used to also be because people would pick "other user", enter username/pass, then click back to anonymous and there was *some* weird browser thing that could, under some circumstances, wind up posting it as the other-user instead of anonymous, which I am only vaguely remembering and is probably one of those things where we're still working around a bug in Netscape 3.0 or something
