### ISSUE TITLE
new comment form icon browser has disrupted keyboard shortcuts

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2640]
Reported in dw-maint: https://dw-maintenance.dreamwidth.org/81236.html?thread=3254356#cmt3254356

Mixed keyboard/mouse workflow for accessing the icon browser used to be browse, select keyword, press enter, press tab once for comment box and twice for post button. New behavior: browse, double click to select, enter, hit tab, and cursor goes somewhere else. This is probably worth messing with the tab-index on.

**Comment by nfagerlund** [comment]
The tab order on the button is about what you'd expect it to be, but when the browser gets dismissed it sends the focus point off into the hinterlands below the bottom of the page (since that's where the browser modal element gets inserted). Boo. Well, easily fixed; ought to be able to just call (button).focus() during the "modal finished closing" handler.

Tab order is currently _almost_ what you'd expect from looking at it: 

- username link
- more options
- browse
- icon menu
- (random, if it's been summoned)
- subject
- body
- post
- preview

Any changes desired?

**Comment by nfagerlund** [comment]
While checking this, I also noticed that you can't tab between icons in the icon browser itself, and THAT is absolutely wack. The icons should probably be marked as buttons, since that's what they function as.

**Comment by rahaeli** [comment]
Nope, that sounds good to me!
