### ISSUE TITLE
Lynx missing some styling on beta update page

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2760]
https://dw-beta.dreamwidth.org/12259.html?thread=484323#cmt484323 reports that the last code push got rid of the rounded corner look on the beta update page in Lynx (see: https://www.dreamwidth.org/entry/new?usescheme=lynx). I'm not sure if this was deliberate to simplify the Lynx CSS or casualty of the various Lynx fixes from the last few pushes.

**Comment by rahaeli** [comment]
(I can very much see the argument that rounded-corners is a fancy CSS trick that doesn't *belong* in Lynx, mind you, which is another argument, but I wanted to log the issue before I forgot to.)

**Comment by nfagerlund** [comment]
Working as intended, Lynx is supposed to be ugly! 😹 Hashtag #wontfix, viva le Sketchy Kytti. 😽

It does need to have most of the javascript that the other skins have (really I think we only omit the menu-hover thing, because there's no menus). And the new entry page _does_ have a fair amount of CSS to get things into the right positions, just because it's a complex page and that couldn't really be avoided without making an ACTUAL mess. But the boxes now use the browser default styling for a `<fieldset>` element, and that's what we wanted to have happen.

**Comment by rahaeli** [comment]
that's what I figured! \*salute\*
