### ISSUE TITLE
Add 'Gold Leaf' style by rosecarmine

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#684]
Submission entry: http://dreamscapes.dreamwidth.org/128228.html
Note: this is a CSS submission and will require conversion to S2.

**Comment by momijizukamori** [comment]
After skimming this again, I think I'm going to go with the submitted S2 layer rather than trying to convert the CSS onto TR (particularly because the S2 submission had a bunch of stuff fixed already). Because it's not a TR child, though - do we have a list somewhere of standard properties to implement? So far I know I need to add stuff to support layout types other than one-column split, but I don't trust my memory at all.

**Comment by afuna** [comment]
We don't have a list of standard properties; TR works as a reference
implementation (and that's the closest we have!)


On Mon, Jun 22, 2015, at 04:34 PM, momijizukamori wrote:
> After skimming this again, I think I'm going to go with the submitted
> S2 layer rather than trying to convert the CSS onto TR (particularly
> because the S2 submission had a bunch of stuff fixed already).
> Because it's not a TR child, though - do we have a list somewhere of
> standard properties to implement? So far I know I need to add stuff
> to support layout types other than one-column split, but I don't
> trust my memory at all.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/684#issuecomment-114302459

**Comment by rahaeli** [comment]
I opened #1422 for that documentation.
