### ISSUE TITLE
Indicate entry security status in comment notifs for locked/filtered entries

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#717]
I'm pretty sure this already exists in HTML mail, but I get text mail from DW and will until the end of days, so this would be a nice thing to have ;)

When you get a comment notif spawned from a comment on a locked (or filtered) entry, it looks like:

> Username (username) replied to a comment you left in a Dreamwidth entry
> "Entry title" ( entry_url ). The comment
> they replied to was:

There's nothing indicating that the entry is locked, so not only does this wind up with me inevitably winding up staring at the "you do not have permission to view this entry" screen if I click through, because I'm inevitably logged in as the wrong account, there's also the (slim, but still) chance that someone could get a notif spawned from a locked entry, enough after-the-fact for them to forget it was a locked entry, and forward the comment to somebody else without realizing.

Let's change that to explicitly indicate it's locked:

> Username (username) replied to a comment you left in a Dreamwidth entry
> "Entry title" (entry_url) [locked]. The comment
> they replied to was:

I think that placement is probably the best option to work well with any variation of comment type ("replied to a Dreamwidth entry", "replied to your Dreamwidth entry", "replied to a comment you left in a Dreamwidth entry", etc) and stands the best chance of getting noticed, since it's right up front next to the URL and near the buttons you'd have to hit to forward the email in most mail clients.

**Comment by kaberett** [comment]
Claimed!

**Comment by kaberett** [comment]
Should this apply to comment notifications only, or also to notifications that a new entry has been posted (if that's a subscription that's set up)?

I assume that for the locked/filtered case, the security indication should just say [locked] per the above (because it's not reader-visible whether a post is to a filter, unless they go looking at http://username.dreamwidth.org/security/group:[groupname]).

Am I correctly understanding that the security indicator should only be printed in cases where the post is locked/filtered, i.e. there shouldn't be an equivalent [public] next to the URL to public posts?

**Comment by rahaeli** [comment]
a) Yeah, let's apply it to both comment and entry notifs.

b) Correct: it should just say locked, not locked/filtered.

c) Yes, let's only indicate it on locked entries; if there's no indication, it can be assumed to be public.

**Comment by kaberett** [comment]
I mean, I'm having a brief moment of "people shouldn't forward comment notifs **anyway** because that reveals the secret address for e-mailing in replies to comments/posts", but a. that's not really the point here ad b. in any case I am Making Progress on the bug! For an imminent step: actually testing that all the permutations work.

Additional questions, however!

(1) I am not at the moment applying indicate-if-locked to official post announcements. If this is something you do want to happen (... presumably for consistency rather than actual utility) I can of course implement it.
(2) I... can't actually remember the appropriate steps for this one -- if I'm editing strings in en.dat, I increment the number at the end and copy-paste the old version into deadphrases.dat?

**Comment by rahaeli** [comment]
1) I don't think locked posts even send out official announcements, and I don't see a situation where there'd ever be a locked official post made (especially since only two people can see locked posts in dw-news!) so feel free to ignore it.

2) Yup!
