### ISSUE TITLE
Don't apply page margins to nav strip

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#827]
It seems some styling applies to the nav strip which can be problematic and make it look very odd and/or cause readability issues (I think someone mentioned font size). One in particular is page margins also applying to the nav strip. This didn't use to be the case. I remember coding margins specifically so they wouldn't do that actually.

**Comment by nfagerlund** [comment]
This isn't practical to fix in the control strip itself,\* but it's trivial to fix in any of the affected themes — you just have to set the global margins on `#canvas` instead of on `html body`. Most of them are inheriting the bad behavior from core2base's `print_default_stylesheet()`.

\* for a hot minute I thought I could cheat my way out with `width: 100vw`, but then you get sideways slop because the vw unit ignores scrollbar widths. Heck.

**Comment by nfagerlund** [comment]
Affected layouts (with default settings and the default theme, many others are probably affected if the user sets those properties) seem to be:

- Lefty
- Leftovers
- Seamless
- Paper Me
- Motion
- Librarian's Dream
- Snakes & Boxes
- Ciel
